### ISSUE TITLE
Issue custom temp Path - issue not deleting temp files - issue shutdown after finish.

### ISSUE THREAD

**Issue by j-mas** [Alkl58/NotEnoughAV1Encodes#1]
Hello Alkl58! 

I only had three issues while testing your GUI: 

1) The Custom Temp Path that I set and save is not saved and is no longer available the next time the program is started. It adjusts itself to the other custom temp path immediately. (see photos)

2) If the custom temp path is set, the temp files are not deleted after the encoding is completed.

3) The shutdown after the encoding process does not work.

![saved Temp file](https://user-images.githubusercontent.com/43079436/76708156-011e3900-66f5-11ea-8b40-5c22ce3243a2.jpg)

(saved custom temp file D:\NEE)

![after restart](https://user-images.githubusercontent.com/43079436/76708174-201ccb00-66f5-11ea-9df4-834bdf6fc3d6.jpg)

(After restarting the program, the set custom temp path automatically changes to the other custom temp paths! Of course I had the previous settings saved in profile and saved this as the default. )

Otherwise thank you for this awesome GUI !!! 

Good work !!!

Best regards!

j-mas

**Comment by Alkl58** [comment]
Please reopen the issue, if the bug still appears!
Latest Build can be downloaded from https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master

Many Greetings! 😃
