### ISSUE TITLE
Future: AVIF

### ISSUE THREAD

**Issue by truefriend-cz** [Alkl58/NotEnoughAV1Encodes#10]
Are you planning to make the same application to convert to AVIF format for images?

**Comment by Alkl58** [comment]
I don't plan to implement image conversion. I may try to create a new project in the future for images instead of videos.

**Comment by truefriend-cz** [comment]
Yes, please. It would be super! 👍 👍 👍

**Comment by Alkl58** [comment]
@truefriend-cz Here you go: https://github.com/Alkl58/MegaPixel

**Comment by gsxgmpkt9020** [comment]
> I don't plan to implement image conversion. I may try to create a new project in the future for images instead of videos.

HOPE FOR animated WEBP to animated AVIF
