### ISSUE TITLE
Can't Able to Enable 2 Pass Encoding on x264

### ISSUE THREAD

**Issue by Daringbaaz** [Alkl58/NotEnoughAV1Encodes#100]
I am Trying to Encode Video on x264 [FFMpeg] on My Threadripper 3970x and Can't Able to Enable x2 Pass Encoding.

I Live Chunks Encoding Features But Facing this issue.

Please Fix it, Thanks

**Comment by Alkl58** [comment]
Fixed in Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.7
