### ISSUE TITLE
Auto Crop and Crop Preview, TS-Support

### ISSUE THREAD

**Issue by Ruppig** [Alkl58/NotEnoughAV1Encodes#102]
Hi, great Project! Thank you very much.
After using the tool for my DVB recordings for converting to AV1 (WebM container) , it would be nice to have an auto crop feature with a video preview to check and correct the outcome.
Supporting a TS-Stream as an input file would eliminate the step to use mkvtoolnix for making a MKV file.

There is also a missing *,dll Error on Windows 7
![error](https://user-images.githubusercontent.com/76917606/163141812-9d9d0f53-7185-4fd2-bc38-bad195c0a265.png)

**Comment by Alkl58** [comment]
All requested features are in the release [v2.1.3](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.3)
