### ISSUE TITLE
Request Add SVT-VP9 Encoder

### ISSUE THREAD

**Issue by KelvinSoh8** [Alkl58/NotEnoughAV1Encodes#103]
Compared With Google libvpx Encoder The SVT-VP9 Encoder Scalable Video Technology is Intel optimized for CPU Processors, Which Get Greatly Improve Encoder Speed Software Encoding.

Google libvpx Encoder Very Slow Encoding VP9

**Comment by Alkl58** [comment]
Dublicate of: https://github.com/Alkl58/NotEnoughAV1Encodes/issues/66

![grafik](https://user-images.githubusercontent.com/34812414/164527280-63afa3ba-4265-43b2-a199-0cc95dbf4f86.png)
