### ISSUE TITLE
[BUG] Parallel Encode Progress Display

### ISSUE THREAD

**Issue by Ichisich** [Alkl58/NotEnoughAV1Encodes#105]
In case multiple files get encoded parallelly instead of chunking, NEAV1E loses the progress as soon as the first file finishes encoding. 
The number of files/workers doesn't matter, the bug even happens with only 2 parallel encodes.

Fortunately, the Video itself is unaffected, only the optic feedback in the NEAV1E GUI is pertained.

The queue works correctly as long as all files are processed:
![working](https://user-images.githubusercontent.com/31080003/167199410-d6901c01-a09d-4b2e-8d9c-56c52c20a264.png)

As soon as one file (in this case 4c) finishes, the other progress bars get greyed out:
![2](https://user-images.githubusercontent.com/31080003/167200175-54c2ac52-933b-45f6-bef5-309f1702c630.png)

The finished queue:
![Screenshot 2022-05-06 203120](https://user-images.githubusercontent.com/31080003/167198141-a140d744-5ba5-414a-b766-f1942445be4a.png)

P.S.
The bug already happened with 2.0.6, so it's not a regression.

**Comment by Alkl58** [comment]
Fixed in [Release v2.0.8](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.8)
