### ISSUE TITLE
After Splitting File It's Freeze For Long Time

### ISSUE THREAD

**Issue by Daringbaaz** [Alkl58/NotEnoughAV1Encodes#106]
**Describe the bug**
I am trying to encode x264 Video 2 Pass Encoding With avg Bitrate, When I Add a file on Queue It's Split and Freeze for 10-15 Min Before Starting Encoding, I Tried on Multiple PC, Same Issue, 

**Expected behavior**
Freeze on 100% Splitting 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://prnt.sc/yKcBluHEWhTp)

Everything Works Fine, But But It's Waste 10-15 Min, When it's Freeze on 100% Splitting

**Comment by Alkl58** [comment]
Hey, 

it's technically not freezing. It is actually encoding audio.

With the following commit I fixed that it doesn't display the encoding progress of the audio: [Fix: Audio Encoding Progress not shown](https://github.com/Alkl58/NotEnoughAV1Encodes/commit/8559358904561df06317969bf138f8c19760f874)

The fix will be included in the next release.

Many Greetings

**Comment by Daringbaaz** [comment]
yeah, I had Identified that and reported on discord too.

make Sure in the Update Both Audio And Video Encoding Start simultaneously. Audio Encoding Speed is very slow, Fix that too

**Comment by Alkl58** [comment]
Encoding Audio and Video in parallel is not possible with the way how the entire logic works. 

It would require deep and complex changes.

Improving Audio speed is not something I can do - thats soley dependant on the audio codec and not NEAV1E.

If you want to imrove that, the only possible / viable option is to use "Copy Audio".

Many Greetings

**Comment by Alkl58** [comment]
Fixed not showing Audio Progress in [Release v2.0.8](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.8)
