### ISSUE TITLE
1 File multiple outputs

### ISSUE THREAD

**Issue by darkjacky** [Alkl58/NotEnoughAV1Encodes#107]
I want to compare 1 file with different settings and so I created 9 different output.
0, 1, 2 ... 8.mp4
But when it is done with encoding there is only 1 file called 8.mp4 (And 9 files .log)
The logs say that it has successfully created 8.mp4 on all of the 9 files.

**Comment by Alkl58** [comment]
Fixed in the new [v2.1.7](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.7) release.
