### ISSUE TITLE
[Feature Request] - Target VMAF

### ISSUE THREAD

**Issue by Felixkruemel** [Alkl58/NotEnoughAV1Encodes#11]
Is it possible to add a target VMAF like Av1an has? Would make the whole fiddling with qp more or less obsolete and would be the best way to archive a target quality.

**Comment by Alkl58** [comment]
I currently don't plan to implement this feature, as it is quite complex.
The way how splitting works is completely different and also needs other dependencies like [PySceneDetect](https://github.com/Breakthrough/PySceneDetect).
I am currently working with the Av1an developer to create a GUI for Av1an with PyQT.

**Comment by Felixkruemel** [comment]
Oh a GUI for Av1an would be quite cool too!

That would really be great, looking forqard to that. Remind me once you have a repo setup for the first ready-to-test files.
