### ISSUE TITLE
[BUG] Burn in Subtitles - Error: No Video Chunk found

### ISSUE THREAD

**Issue by Vereor** [Alkl58/NotEnoughAV1Encodes#110]
Recently wanted to try the 'Burn in' option with the subtitles.

Tested with 2.0.7 and 2.0.8

It results in the error:
Error: No Video Chuck Found

As soon as it goes to do the splitting/chunking

Tried with a few different MKV source files, still the same result.
Maybe a feature not used recently.

**Comment by Vereor** [comment]
Sample log file below
Also to not that Output does not seem to be matching what I set it to.

>7/7/2022 7:23:10 AM : ==========================================================
7/7/2022 7:23:10 AM : INFO  - Started Async Task - UID: BhlVcoifRbFdCqr
7/7/2022 7:23:10 AM : INFO  - Input: D:\VT\IN\Anime\TestWithSubtitle.mkv
7/7/2022 7:23:10 AM : INFO  - Output: D:\VT\IN\Anime\TestWithSubtitle.mkv
7/7/2022 7:23:10 AM : INFO  - Temp Folder: C:\Users\User\AppData\Local\Temp\NEAV1E\BhlVcoifRbFdCqr
7/7/2022 7:23:10 AM : ==========================================================
7/7/2022 7:23:10 AM : DEBUG - GetFrameCount() 
7/7/2022 7:23:10 AM : INFO  - GetFrameCount() => 34046
7/7/2022 7:23:10 AM : DEBUG - ExtractSubtitles.Extract()
7/7/2022 7:23:10 AM : WARN  - ExtractSubtitles.Extract() => File already exist - Resuming?
7/7/2022 7:23:10 AM : INFO  - VideoSplitter.Split()
7/7/2022 7:23:10 AM : DEBUG - VideoSplitter.Split() => FFmpegChunking()
7/7/2022 7:23:10 AM : DEBUG - VideoSplitter.Split() => FFmpegChunking() => Path: C:\Users\User\AppData\Local\Temp\NEAV1E\BhlVcoifRbFdCqr\Chunks
7/7/2022 7:23:10 AM : INFO  - VideoSplitter.Split() => FFmpegChunking() => FFmpeg Command: /C ffmpeg.exe -y -i "D:\VT\IN\Anime\TestWithSubtitle.mkv" -reset_timestamps 1 -map_metadata -1 -sn -an -c:v libx264 -preset ultrafast -crf 0 -sc_threshold 0 -g 300 -force_key_frames "expr:gte(t, n_forced * 300)" -vf subtitles="C\\\:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\NEAV1E\\\\BhlVcoifRbFdCqr\\\\Subtitles\\\\subs.mkv":si=0 -segment_time 300 -f segment "C:\Users\User\AppData\Local\Temp\NEAV1E\BhlVcoifRbFdCqr\Chunks\split%6d.mkv"
7/7/2022 7:23:10 AM : FATAL - VideoSplitter.Split() => FFmpegChunking() => FFmpeg Exit Code: 1
7/7/2022 7:23:10 AM : FATAL - Error: No Video Chunk found

**Comment by Alkl58** [comment]
Hey, sorry for my absence and lack of interaction.

Would it be possible to provide the video file? Or execute the command `ffmpeg.exe -y -i "D:\VT\IN\Anime\TestWithSubtitle.mkv" -reset_timestamps 1 -map_metadata -1 -sn -an -c:v libx264 -preset ultrafast -crf 0 -sc_threshold 0 -g 300 -force_key_frames "expr:gte(t, n_forced * 300)" -vf subtitles="C\:\\Users\\User\\AppData\\Local\\Temp\\NEAV1E\\BhlVcoifRbFdCqr\\Subtitles\\subs.mkv":si=0 -segment_time 300 -f segment "C:\Users\User\AppData\Local\Temp\NEAV1E\BhlVcoifRbFdCqr\Chunks\split%6d.mkv` manually, to see the error message?

I may add better logging capability in the future, sorry for the hassle.

**Comment by Alkl58** [comment]
No response in 4 months, closing issue.

**Comment by Vereor** [comment]
Sorry, I didn't come back to this for a while. Just used other programs to go to x264 instead.
But you AV1 encoder is my preference.

Revisited today to see if the last update made any difference. Looks like the issue might be how PGS subtitles are handled?

D:\VT\IN\Anime>ffmpeg.exe -y -i "D:\VT\IN\Anime\[Judas] Overlord - S01E01.mkv" -i "C:\Users\User\AppData\Local\Temp\NEAV1E\bMpZsiaGpPkCaRr\Subtitles\subs.mkv" -reset_timestamps 1 -map_metadata -1 -sn -an -c:v libx264 -preset ultrafast -crf 0 -sc_threshold 0 -g 300 -force_key_frames "expr:gte(t, n_forced * 300)" -filter_complex "[0:v][1:s:0]overlay[v]" -map "[v]"  -segment_time 300 -f segment "C:\Users\User\AppData\Local\Temp\NEAV1E\bMpZsiaGpPkCaRr\Chunks\split%6d.mkv
ffmpeg version 2022-01-10-git-f37e66b393-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 18.100 / 57. 18.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.100 / 59. 17.100
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 25.100 /  8. 25.100
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
[matroska,webm @ 000002687ec8dec0] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'D:\VT\IN\Anime\[Judas] Overlord - S01E01.mkv':
  Metadata:
    creation_time   : 2020-03-27T01:30:49.000000Z
    ENCODER         : Lavf58.29.100
  Duration: 00:24:15.04, start: -0.007000, bitrate: 1359 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 106.023000
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 106.023000, end 196.029000
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 196.029000, end 602.060000
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 602.060000, end 1331.080000
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 1331.080000, end 1421.003000
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 1421.003000, end 1454.996000
      Metadata:
        title           : Chapter 6
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      title           : [Judas] x265 10b
      BPS-eng         : 1121798
      DURATION-eng    : 00:24:15.037000000
      NUMBER_OF_FRAMES-eng: 34886
      NUMBER_OF_BYTES-eng: 204032361
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-27 01:30:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      title           : [Judas] JAP Stereo (Opus 112Kbps)
      BPS-eng         : 109268
      DURATION-eng    : 00:24:15.041000000
      NUMBER_OF_FRAMES-eng: 72752
      NUMBER_OF_BYTES-eng: 19873858
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-27 01:30:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      title           : [Judas] ENG Stereo (Opus 112Kbps)
      BPS-eng         : 108475
      DURATION-eng    : 00:24:15.041000000
      NUMBER_OF_FRAMES-eng: 72752
      NUMBER_OF_BYTES-eng: 19729598
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-27 01:30:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle, 1920x1080
    Metadata:
      title           : English [Full] (PGS)
      BPS-eng         : 46324
      DURATION-eng    : 00:24:11.074000000
      NUMBER_OF_FRAMES-eng: 652
      NUMBER_OF_BYTES-eng: 8402506
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-27 01:30:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(jpn): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : English [Signs/Songs] (PGS)
      BPS-eng         : 8880
      DURATION-eng    : 00:21:58.692000000
      NUMBER_OF_FRAMES-eng: 112
      NUMBER_OF_BYTES-eng: 1463783
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-27 01:30:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
C:\Users\User\AppData\Local\Temp\NEAV1E\bMpZsiaGpPkCaRr\Subtitles\subs.mkv: No such file or directory
