### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Natsuki-Hui** [Alkl58/NotEnoughAV1Encodes#111]
只要是输出mp4格式都会报这个 无论用什么编码器
![image](https://user-images.githubusercontent.com/40132199/183275969-a8c8cd4e-544e-4f05-80f4-d0fe6d24cdcb.png)

**Comment by Alkl58** [comment]
Fixed in release [v2.0.9](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.9)
