### ISSUE TITLE
[Feature] Translation in french done

### ISSUE THREAD

**Issue by manzing** [Alkl58/NotEnoughAV1Encodes#113]
Hi,

Hi, this is a nice piece of software, I love it for fast and easy encodings.
I made a french translation if you want to add it.
[Strings.fr-FR.resx.zip](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9418222/Strings.fr-FR.resx.zip)

I am not able to propose a pull request as I made (well, tried to make) some other mods on the code to replace x265 by SVT-HEVC for my personal needs and my master branch is rather messy...

**Comment by Alkl58** [comment]
Thanks for your help!

Added it in https://github.com/Alkl58/NotEnoughAV1Encodes/commit/60d6e8220b44d7a932742b8f85395eb0fbb84083

Many Greetings

**Comment by manzing** [comment]
You're welcome, thank you for your work!
