### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Natsuki-Hui** [Alkl58/NotEnoughAV1Encodes#117]
希望可以增加固定输出文件名 比如我拖mp4文件进去默认输出的是mkv文件 但我想把默认的输出文件可以设置成自己想要的格式例如webm![image](https://user-images.githubusercontent.com/40132199/195974029-b93ad9f6-bd01-4131-98c1-dc4cc88202d0.png)

**Comment by Alkl58** [comment]
Added in release: [v2.1.0](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.0), the option is in the program settings next to the option where the default output path can be set.
