### ISSUE TITLE
[Feature] QSV AV1 Hardware Encoding (Intel ARC)

### ISSUE THREAD

**Issue by Jim071** [Alkl58/NotEnoughAV1Encodes#118]
Having just acquired an Intel ARC A380, I ask that you consider including QSVEnc as an AV1 encoder option.
https://github.com/rigaya/QSVEnc/releases/tag/7.21

**Comment by Alkl58** [comment]
Hey, looks pretty cool.

Sadly I don't have an ARC GPU (still not available to buy where I live), however it would help if people could try piping from ffmpeg to QSVEnc: `ffmpeg.exe -y -i "<inputfile>" -an -pix_fmt yuv420p -f yuv4mpegpipe - | QSVEncC64.exe --y4m -i - -c av1 -o "out.webm"`

Of course there are tons of options which need to be tested, but if the basic commands work, QSVEnc could be added without problems.

**Comment by Jim071** [comment]
> Hey, looks pretty cool.
> 
> Sadly I don't have an ARC GPU (still not available to buy where I live), however it would help if people could try piping from ffmpeg to QSVEnc: `ffmpeg.exe -y -i "<inputfile>" -an -pix_fmt yuv420p -f yuv4mpegpipe - | QSVEncC64.exe --y4m -i - -c av1 -o "out.webm"`
> 
> Of course there are tons of options which need to be tested, but if the basic commands work, QSVEnc could be added without problems.



Here is the output from the preciously mentioned ffmpeg command.
it appears to work nicely

[log.txt](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9844523/log.txt)

**Comment by shenef** [comment]
Working on a A770 16GB
[log.txt](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9867479/log.txt)

**Comment by henanzheng** [comment]
I tried it and it can be executed normally.

**Comment by Alkl58** [comment]
The following build has QSV integrated: https://drive.google.com/file/d/1EIsaRuYF6FP5__u-rdHaxzCUNsqFmPRL

If it works for you, then I can add more settings ^^

**Comment by shenef** [comment]
Works great! Good speed and quality. I've played around with encoding speed quality modes and a couple other settings.
The only issues i've encountered are that 12 Bit Color is not selectable and i got errors when trying to encode 60->360fps. (for some reason i can't upload the log for that)

**Comment by Alkl58** [comment]
> Works great! Good speed and quality. I've played around with encoding speed quality modes and a couple other settings. The only issues i've encountered are that 12 Bit Color is not selectable and i got errors when trying to encode 60->360fps. (for some reason i can't upload the log for that)

Intel QSV can only encode up to 10bit. 12bit can only be decoded. But yeah, the bit-depth selection should be redone, so there isn't any confusion.

I'll have a look into the 60fps->360fps shorty, it's a very unique use case tbh ^^

**Comment by henanzheng** [comment]
> 以下版本集成了QSV:[https://drive . Google . com/file/d/1 eisaruyf 6 FP 5 _ _ u-rdHaxzCUNsqFmPRL](https://drive.google.com/file/d/1EIsaRuYF6FP5__u-rdHaxzCUNsqFmPRL)
> 
> 如果它为你工作，然后我可以添加更多的设置^^

I'd like to try, but I can't log on to Google here. Thank you!

**Comment by shenef** [comment]
@henanzheng you can try downloading the automated build from here:
https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts

**Comment by Jim071** [comment]
my first try ended with a blue screen.

[NotEnoughAV1Encodes.zip](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9887814/NotEnoughAV1Encodes.zip)
[Spenser For Hire (1985) - S01E03 - The Choice av1 qsvenc.mkv.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9887818/Spenser.For.Hire.1985.-.S01E03.-.The.Choice.av1.qsvenc.mkv.log)
