### ISSUE TITLE
Handsome dev, and no GF, sad

### ISSUE THREAD

**Issue by master-of-zen** [Alkl58/NotEnoughAV1Encodes#12]

**Comment by master-of-zen** [comment]
ETA for a solution?

**Comment by lastrosade** [comment]
**Consider merging with av1an**

**Comment by Alkl58** [comment]
![5845cd230b2a3b54fdbaecf7](https://user-images.githubusercontent.com/34812414/88578018-2aa68400-d048-11ea-83ec-2351af0226a2.png)
