### ISSUE TITLE
[Feature]建议在队列这里添加删除全部项目的按钮

### ISSUE THREAD

**Issue by Natsuki-Hui** [Alkl58/NotEnoughAV1Encodes#121]
![NotEnoughAV1Encodes_3Ns5tiwXm3](https://user-images.githubusercontent.com/40132199/199999768-4fa3fe4e-8896-4a5c-9cb2-31a5eff7c52d.png)
目前只能一个个删除

**Comment by Alkl58** [comment]
Added a Button to Delete the entire Queue in the new release / 在新版本中增加了一个删除整个队列的按钮 [v2.1.2](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.2)
