### ISSUE TITLE
[BUG] \temp_mux.mkv' could not be opened for reading: open file error.

### ISSUE THREAD

**Issue by shenef** [Alkl58/NotEnoughAV1Encodes#122]
**Describe the bug**
Trying to encode with ~~the QSV AV1~~ any encoder ~~on an Arc A770 16GB~~ i get:
Error: No Output detected - `some number that varies with the file` Error(s) detected. Please check log file! [...]

chunks.txt, splitted.log and exit.log are empty and executing NEAV1 as admin still results in the problem
Checking the temp folder, there is no `temp_mux.mkv` file.

[2022-11-09 20-06-17.mkv.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/9974427/2022-11-09.20-06-17.mkv.log)

Edit: problem not limited to QSV AV1

**Comment by Alkl58** [comment]
Could you try manually executing the command: `ffmpeg.exe -y -i "C:\Users\shen\AppData\Local\Temp\NEAV1E\aJMJhsZFYdBRyDd\Chunks\split000000.mkv"  -an -sn -map_metadata -1 -pix_fmt yuv420p  -f yuv4mpegpipe - | "C:\Users\shen\AppData\Roaming\NotEnoughAV1Encodes\Apps\qsvenc\QSVEncC64.exe" --y4m -i - --codec av1 --cqp 50 --quality best --output-depth 8 --output-csp i420  -o "C:\Users\shen\AppData\Local\Temp\NEAV1E\aJMJhsZFYdBRyDd\Video\000000.webm"` ?

If the folder / files don't exist anymore, you can replace it with a different file / destination.

The only thing which comes to my mind that maybe some Visual C++ Redistributable is missing - does using the integrated encoders in FFmpeg work? (When choosing either `aom (AV1 FFmpeg)`, `rav1e (AV1 FFmpeg)` ...)

**Comment by gabrielrdrguez** [comment]
@Alkl58 I got the same error today. How can I help you debug it?
