### ISSUE TITLE
Request for translation of GUI into Japanese

### ISSUE THREAD

**Issue by rougemeilland** [Alkl58/NotEnoughAV1Encodes#123]
I am very grateful for the Japanese support for the GUI of NotEnoughAV1Encodes.

However, some GUI items should be improved or are not localized in Japanese.
I have attached a new Japanese translation proposal (`NotEnoughAV1Encodes/NotEnoughAV1Encodes/resources/lang/Strings.ja-JP.resx`) to this document, and the changes are described below. Please refer to them:

# [Modifying existing translations]
+ name: `ToggleSwitchLogging`
  + value(en): `Logging`
  + current value(ja): `ログ`
  + new value(ja): `ログを出力`

#  [Adding new translations]
+ name: `ToggleSwitchClearQueue`
  + value(en): `Auto Clear Queue`
  + value(ja): `自動的にキューをクリア`
+ name: `ToggleSwitchAutoPauseResume`
  + value(en): `Auto Pause / Resume`
  + value(ja): `自動的な停止/再開`
+ name: `ToggleSwitchInputSeeking`
  + value(en): `Use Input Seeking`
  + value(ja): `Input Seeking を使用`
+ name: `ToggleSwitchActivateSubtitles`
  + value(en): `Activate Subtitles`
  + value(ja): `字幕を有効にする`

[Strings.ja-JP.zip](https://github.com/Alkl58/NotEnoughAV1Encodes/files/10039957/Strings.ja-JP.zip)

**Comment by Alkl58** [comment]
Added in the new release: [v2.1.2](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.2) - Thanks for contributing!
