### ISSUE TITLE
[Feature] Queue Sorting

### ISSUE THREAD

**Issue by Ichisich** [Alkl58/NotEnoughAV1Encodes#125]
Currently, the queue processes videos in order as they were added.
Especially for parallel encoding, it can be very useful to sort the entries according to their length.

Some other obvious sorting topics could be Name, Type, Size, Date.
But for my personal use case only length is of concern, and I'm not sure what you would consider as bloat.

**Comment by Alkl58** [comment]
Added in the new release: [v2.1.2](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.2)
