### ISSUE TITLE
[Feature\Bug Request]: Checking of frame correctness in chunks

### ISSUE THREAD

**Issue by githupper** [Alkl58/NotEnoughAV1Encodes#13]
Have issue with video\audio desync after encoding with SVT-AV1 and AOMENC. 
Video desync seems to happen at random points in the encoding process. Had tested with audio passthrough and via manual extraction of audio from original video and merging via MKVToolnix with the encoded video.

Would like to request for frame checking of missed frames during or right after the encoding is fone that might have cause this desync issue.

Thank you

**Comment by Alkl58** [comment]
Frame loss/desync only appears (afaik) when ffmpeg has issues splitting without reencoding.
I can look into it to check the framecount after splitting, this should save people some hours of encoding.
For the time being I recommend to enable reencoding during splitting with either x264 or utvideo. This should solve the frame loss issues.
Many Greetings
