### ISSUE TITLE
[Feature] Alert users when they click the close app button when a encoding task is running

### ISSUE THREAD

**Issue by hustcer** [Alkl58/NotEnoughAV1Encodes#130]
Thanks for your great work. It really quite helpful.

**Is your feature request related to a problem? Please describe.**

Alert users when they click the close app button (`X` on the top right corner) when any encoding task is running, currently the app will exit without any alert, and the user has to restart the encoding task from the beginning. They may have clicked the close button without realizing the serious consequences， or they just want to make the app minimize to the system tray.

**Describe the solution you'd like**

Alert users when they click the close app button when any encoding task is running, tell the user that there are running encoding tasks and they will lose their work if they exit.

**Describe alternatives you've considered**

Or simply minimize the app to the system tray. and they can click `Exit` from the system tray

**Additional context**

**Comment by Alkl58** [comment]
Fixed/Added in the new release: [v2.1.2](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.2)
