### ISSUE TITLE
Preset saved audio bitrate doesn't get applied [BUG] 

### ISSUE THREAD

**Issue by koboltzz** [Alkl58/NotEnoughAV1Encodes#132]
**Describe the bug**
Audio bitrate doesn't get applied when you save it in a preset.

**To Reproduce**
Set a custom audio bitrate like 96kbps in preset (e.g. "AudioBitrateStereo": 96 in preset file). Open a video with stereo audio and load up the preset. Audio bitrate doesn't get applied and will stay at 128kbps.

**Expected behavior**
When you load up the preset and then add a video with stereo audio, it should set the bitrate to what it is in preset. Also the other way round, first video and then select the preset.

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - NEAV1E Version: 2.1.1

**Comment by Alkl58** [comment]
Just to clarify: It's about applying the preset **after** opening the video?

Because currently it will apply the preset, if it's loaded first and then the video.

**Comment by koboltzz** [comment]
Ah you are right, first preset - then video, works!
I use your tool the other way round, since the big buttons ('source' etc) on the top look so inviting. First video, then preset. That works but not for audio bitrate.

**Comment by Alkl58** [comment]
Fixed in the new release: [v2.1.2](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.2)
