### ISSUE TITLE
'Custom Settings' are not applied when profile is 'set as default' [BUG] 

### ISSUE THREAD

**Issue by koboltzz** [Alkl58/NotEnoughAV1Encodes#133]
**Describe the bug**
If you have created a profile with custom settings and want to load it with 'set as default' when starting the tool, the custom settings are not applied. 

**To Reproduce**
Enable 'advanced settings' in 'video' tab. Then enable 'custom settings' and change it to something different than the default. In 'summary' tab save a profile and click 'set as default'. Close tool, reopen it -> custom settings are not the settings saved in profile instead the default is shown. After creating an other profile and load up again the first profile, the custom settings are correct.
 
**Expected behavior**
'Custom Settings' are applied when profile is 'set as default' after tool is launched.

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - NEAV1E Version: v2.1.2

**Comment by Alkl58** [comment]
Should be fixed in the release [v2.1.3](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.3)
