### ISSUE TITLE
[BUG] \temp_mux.mkv' could not be opened for reading: open file error.

### ISSUE THREAD

**Issue by gabrielrdrguez** [Alkl58/NotEnoughAV1Encodes#138]
**Describe the bug**
Queue says no output and to refer to the log file

**To Reproduce**
I tried AOM av1 and NVENC AV1 codecs and both raised the same error

**Expected behavior**

**Log File**
[logfile.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/10887665/logfile.log)

**Desktop (please complete the following information):**
 - OS: W11 latest
 - NEAV1E Version: 2.1.2 and 2.1.3
- Ryzen 5800X3D
- RTX 4090

**Comment by Alkl58** [comment]
Could you try manually executing the command?: `C:\Users\User\Downloads\neav1e-portable-2.1.2\Apps\ffmpeg\ffmpeg.exe -y -i "C:\Users\User\AppData\Local\Temp\NEAV1E\sTUGJAKNvOzgYCa\Chunks\split000001.mkv"  -an -sn -map_metadata -1 -pix_fmt yuv420p  -f yuv4mpegpipe - | "C:\Users\User\Downloads\neav1e-portable-2.1.2\Apps\nvenc\NVEncC64.exe" --y4m -i - --codec av1 --cqp 24 --quality default --output-depth 8  -o "C:\Users\User\AppData\Local\Temp\NEAV1E\sTUGJAKNvOzgYCa\Video\000001.webm"`

**Comment by gabrielrdrguez** [comment]
> Could you try manually executing the command?: `C:\Users\User\Downloads\neav1e-portable-2.1.2\Apps\ffmpeg\ffmpeg.exe -y -i "C:\Users\User\AppData\Local\Temp\NEAV1E\sTUGJAKNvOzgYCa\Chunks\split000001.mkv" -an -sn -map_metadata -1 -pix_fmt yuv420p -f yuv4mpegpipe - | "C:\Users\User\Downloads\neav1e-portable-2.1.2\Apps\nvenc\NVEncC64.exe" --y4m -i - --codec av1 --cqp 24 --quality default --output-depth 8 -o "C:\Users\User\AppData\Local\Temp\NEAV1E\sTUGJAKNvOzgYCa\Video\000001.webm"`

Sure, but it failed:
[failed log.txt](https://github.com/Alkl58/NotEnoughAV1Encodes/files/10888937/failed.log.txt)


It seems to work by removing the `--quality default` argument, 
[successful log.txt](https://github.com/Alkl58/NotEnoughAV1Encodes/files/10888939/successful.log.txt)


I had to change the cmd paths though, because I had deleted the temporary files

**Comment by Alkl58** [comment]
Just to confirm, can you try to replace `--quality default` with `--preset default`?

**Comment by gabrielrdrguez** [comment]
> Just to confirm, can you try to replace `--quality default` with `--preset default`?

Seems to work fine with `--preset default`
[sucess with preset.txt](https://github.com/Alkl58/NotEnoughAV1Encodes/files/10889014/sucess.with.preset.txt)

**Comment by Alkl58** [comment]
Already fixed, closing issue.
