### ISSUE TITLE
Window position resets randomly at restart on HiDPI monitors

### ISSUE THREAD

**Issue by JJKylee** [Alkl58/NotEnoughAV1Encodes#14]
No matter where the window ends up at the time of closing, it always defaults to specific positions on the screen when the program restarts.
And the position changes a little randomly on my 120 DPI monitor.

I'm wondering if this helps, but for a reference, StaxRip suffered a [similar issue](https://forum.doom9.org/showthread.php?p=1913921#post1913921), and it was due to a [UI Scale Factor](https://forum.doom9.org/showthread.php?p=1913938#post1913938) behaving weirdly on a HiDPI screen.

**Comment by Alkl58** [comment]
Yeah, the program itself won't open at the same position when restarted. 

There are two options available for the startup location:
1. Manual
2. CenterScreen

Currently the first one is selected, but as I did not give it any values, the values will be [determined by windows](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.windowstartuplocation?view=netcore-3.1).

I have to say that I am not in any means a experienced programmer.

I searched the web for suggestions, but everything I found so far is out of scope for me, as I lack experience and the general understanding.

**Comment by JJKylee** [comment]
Thanks for the kind explanation.
Please keep up the good work. :)

**Comment by JJKylee** [comment]
Thanks.

But is there any way I can put the window at the center instead of putting coordinates manually?
For single windowed apps like neAV1e, CenterScreen comes in handy most of the time, I guess.
I don't want much. :)
Thanks in advance.
