### ISSUE TITLE
Utilize CRF instead of QP for Constant Quality in svt-av1 (FFmpeg)

### ISSUE THREAD

**Issue by Katzenwerfer** [Alkl58/NotEnoughAV1Encodes#143]
Currently, most AV1 encoders have a CRF mode that should have better control over quality than just using a static QP value.

Currently, when using `svt-av1 (FFmpeg)`, adjusting the “Quantizer” slider when in “Constant Quality” mode seems to adjust the QP value, which is not bad, but utilizing CRF instead would be the ideal.

Perhaps a good idea would be to introduce a separate selectable mode, like “Constant Quantization”, for those who want to specifically use a static QP value, while keeping the “Constant Quality” mode to CRF.

**Comment by Alkl58** [comment]
Changed in the latest [release](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.6).
