### ISSUE TITLE
No easy way to encode without splitting[Feature]

### ISSUE THREAD

**Issue by RimasRaV1** [Alkl58/NotEnoughAV1Encodes#145]
No easy way to encode without splitting. One way to do this is to create enormous chunk size.

"No splitting" option in a drop down menu of splitting methods would be great.

**Comment by Alkl58** [comment]
Added in new [Release v2.1.5](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.5).
