### ISSUE TITLE
[BUG] windows defender flagged as malicious 

### ISSUE THREAD

**Issue by TheCodeHermit** [Alkl58/NotEnoughAV1Encodes#150]
Windows defender flagged my install as a trojan

<img width="521" alt="image" src="https://github.com/Alkl58/NotEnoughAV1Encodes/assets/42543560/31e0e875-3287-4329-a933-e958a489a366">

**Comment by Alkl58** [comment]
This is a false positive. Never happened to me. You can safely ignore this.
