### ISSUE TITLE
Updater won't update correctly Libraries

### ISSUE THREAD

**Issue by Mostwest** [Alkl58/NotEnoughAV1Encodes#157]
Is it possible to fix the updaters for libraries, svt-av1 with 1.8.0 was a big improvement

![Screenshot 2024-01-30 144703](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/155648259/14671328-92a5-4236-855d-0876c94197dd)

**Comment by Alkl58** [comment]
If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.

The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.

I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.

**Comment by Mostwest** [comment]
I did try to use a compiled FFMPEG with the latest svt-av1 but the program crashes during encoding.

There are some option on the ffmpeg you included that I need and not every auto-build for compiling has. That's why I didn't use any different ffmpeg because of that.

So if I use FFMPEG with libraries inside, why would I need the .exe of those libraries? I just redundancy or they need to be manually updated using the link you provided?

**Comment by Alkl58** [comment]
> So if I use FFMPEG with libraries inside, why would I need the .exe of those libraries? It's just redundancy or they need to be manually updated using the link you provided?

Some people want to be able to use their own `SvtAv1EncApp.exe` version for testing purpose, thats why there is the option to use non ffmpeg binaries.

I would recommend using only the "FFmpeg" versions, as they are up to date and have less issues, as the non ffmpeg version need the raw video stream piped from ffmpeg which sometimes has issues.

**Comment by Mostwest** [comment]
I understand, before closing this as solved. Can you provide the list of libraries that FFMPEG needs to have in order for the program to run correctly? I'm comparing FFmpeg using -i and I see that some library are missing. Thank you for your patience.

**Comment by PorcelainSky** [comment]
> If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> 
> The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> 
> I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.

https://github.com/Patman86/SVT-AV1-Mod-by-Patman
This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used).  But I don’t know whether it can be used by NEAV1E according to the protocol.

**Comment by Alkl58** [comment]
> https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.

Thanks for that link - I absolutely hate licensing stuff. As long I include the license only for the binary file it should be fine. (I guess)

To be honest, I choosed the MIT lincense because I didn't think about it at all.

**Comment by Mostwest** [comment]
> > If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> > The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> > I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.
> 
> https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.

that's the problem, how do you get the patman mod into FFMPEG? I understand the exe

**Comment by PorcelainSky** [comment]
> > > 如果您使用“svt-av1 (AV1 FFmpeg)”版本，您应该拥有最新的 svt-av1 版本，因为它包含在 ffmpeg 中。
> > > 用于非 ffmpeg 编码的专用库在https://jeremylee.sh/bins/上已经有一段时间没有更新了。
> > > 我需要为新的二进制文件找到不同的来源，但我还没有找到。SVT-AV1 的 Git 仅提供新版本的源代码，而不提供二进制文件。
> > 
> > 
> > [https://github.com/Patman86/SVT-AV1-Mod-by-P](https://github.com/Patman86/SVT-AV1-Mod-by-Patman) ​​atman 这是staxrip使用的，在NEAV1E中工作正常（之前的1.8.0版本有问题，最新版本可以使用）。但不知道按照开源协议能否被NEAV1E使用。
> 
> 这就是问题所在，如何将 svt-av1 patman mod 转换为 FFMPEG 而不是中继到 exe



> > > If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> > > The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> > > I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.
> > 
> > 
> > https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.
> 
> that's the problem, how do you get the svt-av1 patman mod into FFMPEG rather than relay on the exe

I don't quite understand, I am using it directly, replacing it with the old version in the svt-av1 folder. For ffmpeg it should have been updated to svt-av1 1.8.0 version (I guess. Because I have tested with ffmpeg after the release of svt-av1 1.7.0).

**Comment by Mostwest** [comment]
> > > > 如果您使用“svt-av1 (AV1 FFmpeg)”版本，您应该拥有最新的 svt-av1 版本，因为它包含在 ffmpeg 中。
> > > > 用于非 ffmpeg 编码的专用库在[https://jeremylee.sh/bins/上已经有一段时间没有更新了。](https://jeremylee.sh/bins/%E4%B8%8A%E5%B7%B2%E7%BB%8F%E6%9C%89%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0%E4%BA%86%E3%80%82)
> > > > 我需要为新的二进制文件找到不同的来源，但我还没有找到。SVT-AV1 的 Git 仅提供新版本的源代码，而不提供二进制文件。
> > > 
> > > 
> > > [https://github.com/Patman86/SVT-AV1-Mod-by-P](https://github.com/Patman86/SVT-AV1-Mod-by-Patman) ​​atman 这是staxrip使用的，在NEAV1E中工作正常（之前的1.8.0版本有问题，最新版本可以使用）。但不知道按照开源协议能否被NEAV1E使用。
> > 
> > 
> > 这就是问题所在，如何将 svt-av1 patman mod 转换为 FFMPEG 而不是中继到 exe
> 
> > > > If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> > > > The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> > > > I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.
> > > 
> > > 
> > > https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.
> > 
> > 
> > that's the problem, how do you get the svt-av1 patman mod into FFMPEG rather than relay on the exe
> 
> I don't quite understand, I am using it directly, replacing it with the old version in the svt-av1 folder. For ffmpeg it should have been updated to svt-av1 1.8.0 version (I guess. Because I have tested with ffmpeg after the release of svt-av1 1.7.0).

It was stated above by the developer of neav1an

"I would recommend using only the "FFmpeg" versions, as they are up to date and have less issues, as the non ffmpeg version need the raw video stream piped from ffmpeg which sometimes has issues."

That's why I'm asking if there is any FFMPEG with patman svt-av1, otherwise I can someone include the patman version into FFMPEG.exe not separated external exe

**Comment by Mostwest** [comment]
> > https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.
> 
> Thanks for that link - I absolutely hate licensing stuff. As long I include the license only for the binary file it should be fine. (I guess)
> 
> To be honest, I choosed the MIT lincense because I didn't think about it at all.

Can I use the staxrip FFMPEG in your NotEnoughAV1Encodes?
what's the best number of workers for the i7-13700k wich has 8 p core (16 threads) and 8 e core so 24 threads totally?

**Comment by PorcelainSky** [comment]
> > > > > 如果您使用“svt-av1 (AV1 FFmpeg)”版本，您应该拥有最新的 svt-av1 版本，因为它包含在 ffmpeg 中。
> > > > > 用于非 ffmpeg 编码的专用库在[https://jeremylee.sh/bins/上已经有一段时间没有更新了。](https://jeremylee.sh/bins/%E4%B8%8A%E5%B7%B2%E7%BB%8F%E6%9C%89%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0%E4%BA%86%E3%80%82)
> > > > > 我需要为新的二进制文件找到不同的来源，但我还没有找到。SVT-AV1 的 Git 仅提供新版本的源代码，而不提供二进制文件。
> > > > 
> > > > 
> > > > [https://github.com/Patman86/SVT-AV1-Mod-by-P](https://github.com/Patman86/SVT-AV1-Mod-by-Patman) ​​atman 这是staxrip使用的，在NEAV1E中工作正常（之前的1.8.0版本有问题，最新版本可以使用）。但不知道按照开源协议能否被NEAV1E使用。
> > > 
> > > 
> > > 这就是问题所在，如何将 svt-av1 patman mod 转换为 FFMPEG 而不是中继到 exe
> > 
> > 
> > > > > If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> > > > > The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> > > > > I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.
> > > > 
> > > > 
> > > > https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.
> > > 
> > > 
> > > that's the problem, how do you get the svt-av1 patman mod into FFMPEG rather than relay on the exe
> > 
> > 
> > I don't quite understand, I am using it directly, replacing it with the old version in the svt-av1 folder. For ffmpeg it should have been updated to svt-av1 1.8.0 version (I guess. Because I have tested with ffmpeg after the release of svt-av1 1.7.0).
> 
> It was stated above by the developer of neav1an
> 
> "I would recommend using only the "FFmpeg" versions, as they are up to date and have less issues, as the non ffmpeg version need the raw video stream piped from ffmpeg which sometimes has issues."
> 
> That's why I'm asking if there is any FFMPEG with patman svt-av1, otherwise I can someone include the patman version into FFMPEG.exe not separated external exe

I kind of understand your expression.  I think you may have misunderstood the meaning. ffmpeg itself contains svt-av1, just check whether it has been updated.  The reason the developers say svt-av1 is old and ffmpeg should be used is because jeremylee's svt-av1 build stopped at version 1.6.0.  For ffmepg itself, it uses libsvt-av1. You can download the latest ffmpeg version from the official website, or update it through neav1e (the current ffmpeg included in neav1e should already contain the svt-av1 1.8.0 version, or confirm it).  To use it, just select svt-av1(ffmpeg) in neav1e.  If you do not use ffmpeg's svt-av1, you need to download the binary file from https://github.com/Patman86/SVT-AV1-Mod-by-Patman and replace it with the old version (1.6.0).

**Comment by PorcelainSky** [comment]
> > > > > 如果您使用“svt-av1 (AV1 FFmpeg)”版本，您应该拥有最新的 svt-av1 版本，因为它包含在 ffmpeg 中。
> > > > > 用于非 ffmpeg 编码的专用库在[https://jeremylee.sh/bins/上已经有一段时间没有更新了。](https://jeremylee.sh/bins/%E4%B8%8A%E5%B7%B2%E7%BB%8F%E6%9C%89%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0%E4%BA%86%E3%80%82)
> > > > > 我需要为新的二进制文件找到不同的来源，但我还没有找到。SVT-AV1 的 Git 仅提供新版本的源代码，而不提供二进制文件。
> > > > 
> > > > 
> > > > [https://github.com/Patman86/SVT-AV1-Mod-by-P](https://github.com/Patman86/SVT-AV1-Mod-by-Patman) ​​atman 这是staxrip使用的，在NEAV1E中工作正常（之前的1.8.0版本有问题，最新版本可以使用）。但不知道按照开源协议能否被NEAV1E使用。
> > > 
> > > 
> > > 这就是问题所在，如何将 svt-av1 patman mod 转换为 FFMPEG 而不是中继到 exe
> > 
> > 
> > > > > If you use the "svt-av1 (AV1 FFmpeg)" version, you should have the latest svt-av1 version, as it's included in ffmpeg.
> > > > > The dedicated libraries used for non ffmpeg encoding haven't been updated for quite a while on https://jeremylee.sh/bins/.
> > > > > I would need to find a different source for new binaries, which I have not found yet. The Git of SVT-AV1 only provides the source code on new releases and not the binaries.
> > > > 
> > > > 
> > > > https://github.com/Patman86/SVT-AV1-Mod-by-Patman This is used by staxrip, which works fine in NEAV1E (the previous version 1.8.0 had problems, the latest release can be used). But I don’t know whether it can be used by NEAV1E according to the open source agreement.
> > > 
> > > 
> > > that's the problem, how do you get the svt-av1 patman mod into FFMPEG rather than relay on the exe
> > 
> > 
> > I don't quite understand, I am using it directly, replacing it with the old version in the svt-av1 folder. For ffmpeg it should have been updated to svt-av1 1.8.0 version (I guess. Because I have tested with ffmpeg after the release of svt-av1 1.7.0).
> 
> It was stated above by the developer of neav1an
> 
> "I would recommend using only the "FFmpeg" versions, as they are up to date and have less issues, as the non ffmpeg version need the raw video stream piped from ffmpeg which sometimes has issues."
> 
> That's why I'm asking if there is any FFMPEG with patman svt-av1, otherwise I can someone include the patman version into FFMPEG.exe not separated external exe

I think you may have misunderstood the meaning. ffmpeg itself contains svt-av1, just check whether it has been updated.  The reason the developers say svt-av1 is old and ffmpeg should be used is because jeremylee's svt-av1 build stopped at version 1.6.0.  For ffmepg itself, it uses libsvt-av1. You can download the latest ffmpeg version from the official website, or update it through neav1e (the current ffmpeg included in neav1e should already contain the svt-av1 1.8.0 version, or confirm it).  To use it, just select svt-av1(ffmpeg) in neav1e.  If you do not use ffmpeg's svt-av1, then you need to download the binary file of https://github.com/Patman86/SVT-AV1-Mod-by-Patman and replace  the old version (1.6.0), and then  Select the svt-av1 option in neav1e.

**Comment by Mostwest** [comment]
@PorcelainSky 
You missed the point, as stated by the dev he suggested to use ffmpeg's library instead of going external, on this note also patman svt-av1 seem the correct version to use, so far so good, just download ffmpeg with patman in it, wrong because now you have the original ffmpeg in the app Wich has different lib and options than the new one.

So the best solution is either a full list of the ffmpeg libraries and options required to run the programm correctly or a way to update and swap single libraries... You see the point?

I have already used a compiled FFMPEG with the latest libraries updated and the software crashed.

**Comment by PorcelainSky** [comment]
> @PorcelainSky 你错过了这一点，正如开发人员所说，他建议使用 ffmpeg 的库而不是外部，在这一点上，patman svt-av1 似乎是正确使用的版本，到目前为止一切都很好，只需下载带有 patman 的 ffmpeg，错误因为现在您在应用程序中拥有原始的 ffmpeg，它具有与新版本不同的库和选项。
> 
> 因此，最好的解决方案要么是正确运行程序所需的 ffmpeg 库和选项的完整列表，要么是更新和交换单个库的方法......您明白这一点了吗？
> 
> 我已经使用了已编译的 FFMPEG 并更新了最新的库，但软件崩溃了。



> @PorcelainSky You missed the point, as stated by the dev he suggested to use ffmpeg's library instead of going external, on this note also patman svt-av1 seem the correct version to use, so far so good, just download ffmpeg with patman in it, wrong because now you have the original ffmpeg in the app Wich has different lib and options than the new one.
> 
> So the best solution is either a full list of the ffmpeg libraries and options required to run the programm correctly or a way to update and swap single libraries... You see the point?
> 
> I have already used a compiled FFMPEG with the latest libraries updated and the software crashed.

Ok, I get it now , thanks!

**Comment by lastrosade** [comment]
Updated and uploaded, let me know if you have any issues.

**Comment by Ichisich** [comment]
@lastrosade 
Thanks, Jeremy, works as intended.
