### ISSUE TITLE
Encoder Speed Name gets stuck after using Encoder with Speed level Name

### ISSUE THREAD

**Issue by MrBullet75** [Alkl58/NotEnoughAV1Encodes#158]
Source and Destination defined or not, when a video encoder is selected, which uses words for levels rather than numbers, the selected level will not be replaced by the corresponding number when switching back to an encoder that uses Speed level numbers. Not sure if there is any impact on the actual encoding. When switching back to an encoder that uses words for speed levels it works again, but getting to see the numbered encoder speeds requires a restart of the software.

1. Go to 'Video'
2. Click on 'Encoder'
3. Select 'x265 (HEVC FFmpeg)', 'x264 (AVC FFmpeg)', 'QuickSync (AV1 Intel HW)', 'NVENC (AV1 NVIDIA HW)' or 'AMF (AV1 AMD HW)'
4. Select any 'Speed' option
5. Click on 'Encoder' again
6. Select 'aom (AV1 FFmpeg)', 'rav1e (AV1 FFmpeg)', 'svt-av1 (AV1 FFmpeg)', 'vpx-vp9 (VP9 FFmpeg)', 'aomenc (AV1)', 'rav1e (AV1)' or 'svt-av1 (AV1)'
7. Select any 'Speed' option
8. See Speed Preset Name from previous encoder not changing

1) Shows the Video Tab right after startup:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/8cc518b0-6138-44ef-99a8-2e2f0b93cd23)
2) Speed can be changed and Number changes accordingly:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/77cdd90f-c97b-45fc-873e-cbbee91fa975)
3) Also works with another Encoder:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/7f0446a0-2df7-4406-97b1-4d8b54f63bb1)
4) Encoder selected with word describing Speed:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/637b4c79-5fb4-48e2-9a53-d16adb30fb65)
5) Speed changes accordingly:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/77e8c706-56bc-40b6-b71b-2cfc8a000773)
6) Also works with other Encoder:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/27584843-4c55-4658-8477-0726a55ca08e)
7) Encoder with Number for Speed still shows word:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/ca1c9eed-1ae2-469a-b33e-6ec716dfef03)
8) Speed change does not update the word:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/9988e283-af97-4113-b739-0ff2b3f6eccd)
9) Other Encoder with numbered Speed:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/854c83ce-f3da-435a-835f-ea7b86830d11)
10) Encoder switched to worded Speed:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/f4ff77a0-2513-4a6b-b6c9-f84229aadb8f)
11) Speed changes accordingly:
![image](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/102806135/b3bf3044-3515-479b-9e41-a2397583fa98)

Desktop:
 - OS: Win10 20H2
 - NEAV1E Version: v2.1.6 (issue goes back to introduction of H.264/H.265)

**Comment by MrBullet75** [comment]
> Thanks for reporting this issue.
> 
> This issue should only affect the user interface and not the actual encode, thats why I won't release a hotfix.
> 
> I already pushed a fix, this will be included in the next release.

I thought so too but I didn't know. Btw I really like the whole project. Keep it up :)

**Comment by Alkl58** [comment]
Fixed in the new [v2.1.7](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.7) release.
