### ISSUE TITLE
[BUG] Batch Folder Menu Cut Off

### ISSUE THREAD

**Issue by Ichisich** [Alkl58/NotEnoughAV1Encodes#159]
Regression with the latest version 2.1.6

![Screenshot 2024-02-04 101307](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/31080003/23c3c71a-f337-4e2b-af1a-2854038bcebc)

**Comment by Alkl58** [comment]
Fixed in the new [v2.1.7](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.7) release.
