### ISSUE TITLE
[BUG] Batch folder does not read MPG extension (video codec is MPEG1)

### ISSUE THREAD

**Issue by Scordem** [Alkl58/NotEnoughAV1Encodes#160]
**Describe the bug**
Single files will read the mpg extension (video codec is MPEG1) without any problem, but batch folders will not read the mpg extension.

1. Click on 'Souce'
2. Click on 'Batch folder'
3. Select the folder with the mpg file
4. The next window that appears is empty

**Expected behavior**
I want the same behavior for mpg (video codec is MPEG1) files as when I load mp4 or mkv from a batch folder

**Desktop (please complete the following information):**
 - OS: Windows11 22631.3155
 - NEAV1E Version: 2.1.6

**Comment by Alkl58** [comment]
Fixed in the new [v2.1.7](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.7) release.
