### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by j-mas** [Alkl58/NotEnoughAV1Encodes#2]
The last build 1.0.7 doesn´t create an muxed output file!

**Comment by Alkl58** [comment]
I need more information!
What are the settings?
Did you press Cancel? (resume mode?)
How is your Input/ouput file path? (custom temp folder?)
Subtitles? Audio?

**Comment by Alkl58** [comment]
Yeah, the subtitle feature should only be used, if subtitles exist.
Greetings ^^
