### ISSUE TITLE
First underscore dropped from input & output filenames

### ISSUE THREAD

**Issue by scan80269** [Alkl58/NotEnoughAV1Encodes#26]
Version 1.3 appears to be dropping the first underscore ("_") character from filenames entered into "Open Source" and "Save To..." filename dialogs.  For example, entering 1_2_3_4_5_6_7_8.mp4 results in 12_3_4_5_6_7_8.mp4 being displayed in the the Overview tab.

![NEAV1E_Filename_Bug](https://user-images.githubusercontent.com/71793880/99464619-69a95f80-28ed-11eb-8a66-bfb043416bbd.png)

**Comment by Alkl58** [comment]
Thanks for submitting a bug ^^

I identified the issue being a technical limitation of the WPF Labels I am using.

I am currently rewriting the entire application on this Branch: https://github.com/Alkl58/NotEnoughAV1Encodes/tree/rebegin

This issue you are experiencing should be resolved once I have made a new release. 

Many Greetings

**Comment by Alkl58** [comment]
Please try the latest Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v1.4

**Comment by Alkl58** [comment]
I close this issue as this issue has been resolved as far as I can tell.

Please reopen this issue if you think it has not been resolved. 👍
