### ISSUE TITLE
Program crashes while encoding audio

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#27]
Greetings,

NEAV1Enc Ver. 1.3 crashes after I started a job with just one video to encode while encoding audio. 
I'm using Windows 10 Ver. 20H2 with latest patches, program dependencies also latest version.

[program.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/5590611/program.log)

**Comment by Alkl58** [comment]
The log file suggests that the crashing occurs directly after the Rename Function of the Chunks and doesn't seem to be directly cause by encoding audio.

Is it possible to provide the video file? This would really help inorder to find the actual cause of the issue ^^
If you don't want to do it on Github, you can also write to me on the [AV1 Discord](https://discord.gg/HSBxne3)

**Comment by Alkl58** [comment]
Another possibility is that you had previous Temp Files which can cause crashes.
I am currently working on a complete reimplementation of the program on the [rebegin](https://github.com/Alkl58/NotEnoughAV1Encodes/tree/rebegin) branch.
Once this branch is finished in development I will merge it, it should (hopefully) solve this issue

**Comment by Palulukas** [comment]
Hello AIKI58,

unfortunately I don't have a Discord account. Is there another way to send you the videofile? 
I also cleaned the Temp Files and it crashed so I don't think that's the problem.

**Comment by Alkl58** [comment]
If you want you can diretly upload it to my "[Server](https://hfs.eroneko.moe/Upload/)"

You can simply click on Upload Files, then you have to select the file. Finally you can hit "Upload Files" to upload the selected file.

Note that I will shutdown the server once you Uploaded the file and remove the link.

An alternative would be that you upload it to Google Drive or similar.

Many Greetings

**Comment by Alkl58** [comment]
Edit: I removed the link as people were trying to do php code injection.

I also can't let my laptop running for hours/days waiting for you to upload it.

You can try uploading it to Github or Google Drive.

**Comment by Alkl58** [comment]
Please try the latest Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v1.4

**Comment by Alkl58** [comment]
Feel free to reopen the issue if the issue has not been resolved for you.
