### ISSUE TITLE
Constant "No Output File found"

### ISSUE THREAD

**Issue by SplitCoreGaming** [Alkl58/NotEnoughAV1Encodes#28]
[program.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/5617370/program.log)

First time using. Constant issue no matter how many times set/saved. Keeps asking "No Output File found" on Video encoding section.

Tried multiple parts, settings and even containers with different file names.

Thanks

**Comment by greenie214** [comment]
Same issue as above with similar variation of filenames w/wo audio/subtitles etc
[program.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/5617457/program.log)

Hope this helps :)

**Comment by Alkl58** [comment]
It could be the new issue where ffmpeg changed the behavior of piping certain information which, for example, aomenc does not support.

You can try this Build, which is from the rebegin branch: [Click](https://cdn.discordapp.com/attachments/783018291806732348/783018481284808716/NotEnoughAV1Encodes_1.4_Pre-Release.zip) (download & exract, it includes the dependencies)

This Build I am providing does not have Subtitle support, as nearly everything has been rewritten on the back-end.

Please report back if it works for you ^^

**Comment by SplitCoreGaming** [comment]
> It could be the new issue where ffmpeg changed the behavior of piping certain information which, for example, aomenc does not support.
> 
> You can try this Build, which is from the rebegin branch: [Click](https://cdn.discordapp.com/attachments/783018291806732348/783018481284808716/NotEnoughAV1Encodes_1.4_Pre-Release.zip) (download & exract, it includes the dependencies)
> 
> This Build I am providing does not have Subtitle support, as nearly everything has been rewritten on the back-end.
> 
> Please report back if it works for you ^^

Many thanks for quick reply. Left all at default and started a encode. Updating freezes, but if you taskmanager kill 7-zip it updates fine.
Will update in 2 hours to see if encode is successful on default settings.

**Comment by greenie214** [comment]
Worked a charm at default and again with some custom settings- Equal chunking, max worker count, 10-bit, 2-pass, cq 25.
Looking forward to the updated version and fingers crossed for subtitle support returning soon.

Cheers for the quick fix on my end at least

**Comment by SplitCoreGaming** [comment]
Further update. 
Relownloaded current Version on GitHub. IF you only update the codecs, and DO NOT press the FFmpeg update button, seems to be working great 💯 
Many thanks for explaining what issue may be.

**Comment by greenie214** [comment]
> Further update.
> Re-downloaded current Version on GitHub. **IF** you only update the codecs, and **DO NOT** press the FFmpeg update button, seems to be working great 💯
> Many thanks for explaining what issue may be.

Interesting so FFmpeg likely to be the main issue since I didn't update the codecs OR FFmpeg

**Comment by SplitCoreGaming** [comment]
Can confirm numerous tests later, this solution worked. Looking forward to new version :)

> Further update.
> Re-downloaded current Version on GitHub. **IF** you only update the codecs, and **DO NOT** press the FFmpeg update button, seems to be working great 💯
> Many thanks for explaining what issue may be.
