### ISSUE TITLE
Checkboxes doesn't mark off

### ISSUE THREAD

**Issue by Katnjia** [Alkl58/NotEnoughAV1Encodes#3]
OS: Windows 7

Title describes the issue. Checking off boxes doesn't appear visually, and stay blank.

![image](https://user-images.githubusercontent.com/22605524/77379902-23115e80-6d7a-11ea-8840-1fd25a01704b.png)

Running the program with compatibility options doesn't seem to resolve the issue.

**Comment by Alkl58** [comment]
It works fine on my Windows 7 VM: [Video](https://youtu.be/0EZjqw6CpAs)

Do you have some custom Windows Theme?

**Comment by master-of-zen** [comment]
Closing issue without solving
![](https://i.ya-webdesign.com/images/jebaited-transparent.png)
