### ISSUE TITLE
Shows encoding complete but does not output anything if filenames have cyrillic characters.

### ISSUE THREAD

**Issue by gimix311** [Alkl58/NotEnoughAV1Encodes#31]
Trying to encode a file with cyrillic characters in the name (russian, in this case). NEAV1E jumps to the end, and completes encoding, without outputing anything. This might be unicode related, so other foreign languages might face the same issue.

**Comment by Alkl58** [comment]
Sadly .NET Framework does  [not natively support cyrillic characters.](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.7.2#list-of-encodings)

As I said i this issue: #9 , the easiest way to fix this issue would be to rename the file with standard utf-8 characters, as it might also break other stuff.

I am still researching online, but I don't think that this is (easily) fixable.

Sorry for the inconvenience

**Comment by gimix311** [comment]
That was exactly how I worked around it. It's a minor annoyance at best. Threw me off for a while though, because there were no errors in the log file.
