### ISSUE TITLE
pyscenedetect causes videos to be incorrectly coded as twice as long

### ISSUE THREAD

**Issue by gimix311** [Alkl58/NotEnoughAV1Encodes#32]
Using pyscenedetect makes the muxed video look like it is almost twice as long as it should be, time wise. Using time chunks or ffmpeg's scene detection doesn't have this problem. It also wasn't VFR related, the problem is only happening when pyscenedetect is used. For example, the video I am encoding is 11m 52s long, but the output file is 23m 44s, even though it cannot seek so far. The actual video is only 11m 52s in the output file, even though ffprobe, mpv and other plays show the output as 23m 44s long.

**Comment by Alkl58** [comment]
Have you deleted any remainings for a previous encode?
Because in theory it could have written the chunks to the aleady existant "splits.txt" file.

Would it be possible to provide the video file and log file?

**Comment by gimix311** [comment]
[Here](https://we.tl/t-Td7bmHXwyJ) you go.

**Comment by Alkl58** [comment]
Would it be possible to provide the source file? This would really help ^^

Sorry for the inconvenience

**Comment by gimix311** [comment]
Sure thing. [Here](https://we.tl/t-ZvYRqUBjYF) you go.

**Comment by gimix311** [comment]
It seems to be a combination of VFR and pyscenedetect that's triggering the problem. I just encoded another run and the only thing I disabled was VFR and the output was correct this time.

**Comment by Alkl58** [comment]
Yeah, I was going to say something about VFR.

The VFR switch is only meant to be used, if the input video has a variable framerate (which your source does not have).

My guess is that due to this reason mkvextract failed to properly extract the timecodes of the frames, thus later assumed that the video has 11.988fps. It was easily fixable by using mkvtoolnix at manually setting the framerate to 24000/1001.

**Comment by gimix311** [comment]
Ah ok! I was under the assumption that the VFR toggle was to create a VFR output, saving some data in the process. A tooltip should sort most people out.
