### ISSUE TITLE
neav1e encoding modern video for web issues

### ISSUE THREAD

**Issue by dramspro** [Alkl58/NotEnoughAV1Encodes#34]
Hi @Alkl58 and thanks for nice an really good look encoder.
I meet nav1e (and put #100 star :-) ) from v1.4 when i was find an svt-av1 windows GUI because HandBrake cant encode AV1 and other tools not using mutlithreat mode.

My target: encoding video for upload its to my website and i want to support modern video formats. My second target - fastest way and using full power of my PC i working in Ryzen ThreadRipper 1900x 8c/16t processor and can test also at Ryzen 9 3950x 16c/32 and AMD radeon RX580 8gb video cards

Ideal for me would be usecase like this:

Preparation
0. Create several presets (in my case - 9pcs)
File name: [orig-name][append].[container]
Endocer: svt-av1 (and encoder-related setting like quality=45 and other)
Filter: Scale 0x720p Lancozs
and some other settings

Usage
1. open encoder and drag&drop video.mp4 (h264+AAC 30fps with high, not optimized for web bitrate like 21mbps from my video editing software)
2. select several presets at the same time to apply
3. click Start and get 9 output files
3.1 Maximum (about 96%) browser-compatible formats in 3 steps of resolution (videocard-fast-encoded in h.264 ~5mbt bitrate like youtube recommended with AAC codec)
3.1.1. video_1080p_h264.mp4
3.1.2. video_720p_h264.mp4 
3.1.3. video_360p_h264.mp4 
3.2. Good (about 75%) browser-compatible and good file size optimized format in 3 steps of resolution (VP9+OPUS)
3.2.1. video_1080p.webm
3.2.2. video_720p.webm
3.2.3. video_360p.webm
3.3. Most perspective but currently low (about 40%) browser-compatible and best file size optimized format in 3 steps of resolution (AV1+OPUS)
3.3.1. video_1080p_av1.mp4
3.3.2. video_720p_av1.mp4
3.3.3. video_360p_av1.mp4

And what nav1e features is missing for this case:
- drag&drop input file support (like in HandBrake if you seen its)
- in presets, simple text append support for file names
- mp4 container support (was remover from v1.5 and i am very sad)
- may be svt-vp9 support (implements like svt-av1 but my skills too low even for test svt-vp9 perfomance compare with ffmpeg+libvpx-vp9 with "-row-mt 1" and "-threads 16" whitch i using now and get a 60-70% CPU utilization, and for speedup i start two encoding processes simultaneously and get 98% CPU load!) OR libvpx-vp9 support
- simple h264_amf (or other [HW accelerated codec](https://trac.ffmpeg.org/wiki/HWAccelIntro)) and libfdk_aac support

**Comment by dramspro** [comment]
@Alkl58, thanks for awesome updates! Especially for returned .mp4 container, even new batch mode yet not support .mp4 #39  its make latest version of nav1e usable for me again! Drag and drop is cool too 👍

**Comment by Alkl58** [comment]
FYI: The output name of the files encoded with different presets are equal to the preset name.
Files are placed like this: `"\selected\path\{filename}\{preset_name}.{selected_container}"`

Example: Two Presets (av1.720p.xml & av1.480p.xml)
Result: 
`\video.mkv\av1.720p.webm`
`\video.mkv\av1.480p.webm`

You can try the latest appveyor build: [click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master) (only replace the main .exe file)

Many Greetings

**Comment by dramspro** [comment]
@Alkl58 its great!
But in my case, i need for many renaming operations (because defferen video files has same names `{preset_name}.{selected_container}` , maybe i can change last `\` for `_` ?

Like this:`"\selected\path\{filename}_{preset_name}.{selected_container}"` will be best.

Thank you very much

**Comment by Alkl58** [comment]
Note: 2.0.0 has a regression with this feature.
The goal is to re-add it in the next 1 or 2 releases.

**Comment by Alkl58** [comment]
Regressions with output filename in batch mode has been fixed.

You can now set a name pattern when creating a preset:

![grafik](https://user-images.githubusercontent.com/34812414/146690372-35bb7eb0-4351-4e0e-91ad-bf0fe97ee74f.png)

The idea is, that you can create multiple presets, each with their own resolution / setting and each of them has their own name pattern for batch encoding. When adding files via batch to the queue it should show the desired behavior.

**Comment by Alkl58** [comment]
I just pushed a commit, which will create an output directory if it doesn't exists.

In theory, it should be possible to specify a folder in that batch name field. 
Something like `{filename}\AV1\1080p.webm`

The options now should pretty much satisfy everyone's naming needs.

I will close the issue, once I deemed it functional and re-added drag & drop.

**Comment by Alkl58** [comment]
Tested working after fixing a small issue (9fe52a12a86c3d3b77eb68218ea0d3fd14e09987)

I also re-added drag & drop in https://github.com/Alkl58/NotEnoughAV1Encodes/commit/4d2b6b53a78c5b1d9a8c32be81f849824da91ded

Closing this issue, have a good day!

**Comment by dramspro** [comment]
@Alkl58 thank you again for awesome work, i test new version and get feedback soon

**Comment by dramspro** [comment]
Hey, @Alkl58, can i use advanced settings for start ffmpeg with "h264_amf" (AMD hardware accelerated coder). Now i use NEAVIE for encoding to AV1 and VP9 and forced to use anotgher encoder (or **ffmpeg** from console) for simple **h.264** codec (with **aac** audio) for _graceful degradation support_ on my website.

If custom settings in advanced mode allows this, can you help me to choose parameters?
 
Or h.264 in NEAV1E can be added in gui? potentially :) someday ;-)

**Comment by n00mkrad** [comment]
What's the point of adding h264 to an AV1 GUI...
Use nmkoder if you want a GUI with lots of encoders and ffmpeg options.

**Comment by dramspro** [comment]
> What's the point of adding h264 to an AV1 GUI...

@n00mkrad, in my case — for use one program instead of "stack", and with cool presets get 9 output files (see my start comment) from one input. But thanks for suggest, i'll test nmkoder too

Now, with NEAV1E, i can encode a "difficult" (vp9 and av1) formats, but a "simple" h.264 i cant. It is not big problem for me, but i want to help with my expirience for improving @Alkl58's tool!

**Comment by Alkl58** [comment]
As VVC is also planned at some point, I don't see an issue also adding x264/x265 encoding support - however this can take a few days, as I am also working on making a Linux spinoff in PyQt. (I am currently working on Linux inside a Windows VM for NEAV1E)

**Comment by Alkl58** [comment]
@dramspro with the release v2.0.2 very basic x265 / x264 was added. In theory all you need to do is to set your desired hardware accelerated encoder in advanced settings, after selecting the x264 or x265 encoder.

**Comment by Alkl58** [comment]
Closing the issue now. Feel free to open new ones for new issues and improvement suggestions.
Many Greetings
