### ISSUE TITLE
[Feature request] Vapoursynth support

### ISSUE THREAD

**Issue by gersch07** [Alkl58/NotEnoughAV1Encodes#36]
Dear Alkl58, first of all thanks for making NEAV1E public and keep up this great work!

Are you planning to integrate Vapoursynth to create the pipe to the encoders? On my Core i7 8700K the ffmpeg processes often take up ~70% of the cpu, with only ~30% left for the actual encoders. Vapoursynth (or, more precisely, "VSpipe") is much more efficient (currently ~5%), so that a huge speedup would be possible.

**Comment by Alkl58** [comment]
> Are you planning to integrate Vapoursynth to create the pipe to the encoders?
Currently not, as this would be a really deep change, as this would require a new way of setting start and end time of the chunks

> ffmpeg processes often take up ~70% of the cpu
what video source do you use? FFmpeg should not use that much. This seems more like you are decoding some sort of heavily compressed media. Encoding with 8 workers results in at max 1-5% cpu usage by ffmpeg (all processes together)

I will keep it in mind, but I can't really guarantee anything.
