### ISSUE TITLE
Copy Audio (FLAC) within Batch Processing

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#37]
Hello again,

thank you for your latest Update. :-)
Since Version 1.5 I have issues with processing a bunch of mkv files with flac audio inside. 
When I tune the settings, set the input and output locations, and then start the encoding, it detects the scenes of the first file and then the gong sound for finished batch immediately plays. Nothing encoded. 
Do I have to set the audio bitrate to 0 for audio copy or leave it default (128)? Neither of the options actually work...

The program.log is not very helpful...

Regards

**Comment by Alkl58** [comment]
I am currently investigating a bug with subtitles in batch mode.
I will try to see if I can reproduce your specific problem ^^

**Comment by Palulukas** [comment]
Thank you for your further investigation. 
If you need the Sourcefiles... let me know (although that download is gonna be rough ^^).

**Comment by Alkl58** [comment]
If the latest AppVeyor Build does not fix your issue, I would be grateful for getting the source files.
I replied to your other issue here: https://github.com/Alkl58/NotEnoughAV1Encodes/issues/38#issuecomment-779954192
Many Greetings

**Comment by Palulukas** [comment]
Hello again, 
I am sorry to say that it doesn't work for me. 
It is not the same anime this time but it has two flac audio tracks builtin. 
When I start the encoding process it creates the mkv files but there is no audio inside. 
PM me if you need the source files.

Regards

**Comment by Alkl58** [comment]
Could you retry the latest AppVeyor Build.
It seems that the audio "encoding" failed with mulitple audio tracks, because of a missing space...

**Comment by Palulukas** [comment]
With the current AppVeyor Build, it works! 
Is it normal to leave the Bitrate setting as is when selecting "copy audio"? 
It may be more reasonable for the bitrate setting to clear itself when "copy audio" is selected. 


Regards
