### ISSUE TITLE
Might not be an issue, only FYI

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#38]
Hello again, 

this might not be an issue and it is only for your information:
Please note the progress bar. 

![NEAV1E-FYI01](https://user-images.githubusercontent.com/11398289/107023547-184f9480-67a7-11eb-85c9-6769225d43a2.jpg)

Grüße aus dem Saarland

**Comment by Alkl58** [comment]
Are you using some kind of deinterlace filter? (or any other Filter?)
Sorry for the inconvenience.

**Comment by Palulukas** [comment]
Hello Aiki58, 

no I am not using any kind of filter, only splitting.

**Comment by Alkl58** [comment]
I think I might have solved your issue.
You can try the latest AppVeyor Build: [Download](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts)
Just extract the main .exe file and replace the main program exe file with it.
Hopefully this works for you!
Many Greetings

**Comment by Alkl58** [comment]
Issue should be resolved now with the latest release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v1.7
Many Greetings
