### ISSUE TITLE
No result after 12 hours of encoding after using "resume"

### ISSUE THREAD

**Issue by j-mas** [Alkl58/NotEnoughAV1Encodes#4]
Boah! That was a hard blow!
I encoded a 2.5 hour video with aomenc. After 8 hours I had to stop and shut down the PC. The next day I used the resume function. The program opened correctly and also gave both folders, i.e. source video and output video. But when I ran start encode it found neither source video nor output video and asked for it. I have specified both folders again. After that the program resumed. After further four hours, the encoding process was completed and the muxing process was started and carried out to the end. So after a total of 12 hours I received the message that the process was finished. All the more my astonishment when I found out that unfortunately no result was received under the output folder !!!!!!!!!!!
No result there and all temp files deleted because I had set it up with the confidence that the program would work correctly. So 12 hours full power of my computer for nothing!!!
In the future I will always keep the temp files so that at least the video, audio and subtitle files can be merged with mkv Toolnix.

Alkl58, please check the resume function again and please fix the error! 

The program is otherwise great. For processes without a resume it works excellently !!!

Best regards

j-mas

**Comment by Alkl58** [comment]
Dear j-mas,
Im sorry to hear that you have such problems and wasted so much time.

I found the bug, why it says that there is no input/output, but this bug doesn't result in ffmpeg not muxing the files.

Which Build were you using?
What Settings were you using? (Audio? Subtitles?)

**Comment by j-mas** [comment]
Hello Alkl58!

Thank you for your answer.
 
I think I found the problem. At the beginning of the encoding process, the program asked the question: There is a problem with the subtitles. Should I skip this? I answered yes and the encoding process started.

I am just about to encode the same home video and the same question came again. I chose to skip again. But then I found in the temp file that a file subtitles was created anyway, but of course it is empty. I could imagine that this would lead to the problem when merging the three files, video, audio and subtitles. I then simply deleted the subtitles folder and will see in about 8 hours whether that was the problem.  I will report when the encoding process is finished!

By the way, it is not a problem to invest the time to find the bugs of the program. It is a beta version and there are always bugs. It is fun to help improve a program that I could never have created myself. I can't say enough "thank you" to someone who develops such a program and also makes it available to the general public free of charge!

Best regards!

j-mas

**Comment by Alkl58** [comment]
I hope that you don't use a Build before this Commit: https://github.com/Alkl58/NotEnoughAV1Encodes/commit/f385faba79324e36b80ca5898fefc0abab40a725

**Comment by j-mas** [comment]
No, I use the newest AppVeyor build 1.0.29.

**Comment by j-mas** [comment]
No, it doesn´t work. I got no output result for the whole video. Because I did not delete Temp file automaticaly I could merge video and audio file with MKVToolNix GUI.

**Comment by Alkl58** [comment]
I need to know following things:
- Do you have a custom Temp Path specified?
- Was the last attempt also in Resume Mode?
- Do you have the tool MediaInfo? (I would like t know which indexes the original file has)

I found a potential Bug, which may be a Problem with Subtitles, if you close the entire program and then resume the encode.

You can also join the [AV1 Discord](https://discord.gg/HSBxne3) if you want. There you can write me directly, if you want.

**Comment by j-mas** [comment]
With the last AppVeyor build 1.0.32 the problem seems to be solved!
