### ISSUE TITLE
Updater unable to check for new versions

### ISSUE THREAD

**Issue by etwasmitbaum** [Alkl58/NotEnoughAV1Encodes#40]
Hello,
the updater is no more working. The "Upate Version" shows no text for a new version.

![image](https://user-images.githubusercontent.com/47484288/111604788-f1d53e00-87d5-11eb-9b41-ec429c8fe523.png)

**Comment by Alkl58** [comment]
Hi @etwasmitbaum

the issue should be resolved now ^^

The problem was that an expired TLS certificate, which has been now renewed by the owner.

Many Greetings

**Comment by etwasmitbaum** [comment]
Thank you very much!
It's working now.
