### ISSUE TITLE
[Feature Request] Track name for audio tracks

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#41]
I would like to be able to name a audio track, for example when you have a audio track with commentary from the director. 
Can you please integrate this in your great program? :-)

Thank you.

Kind regards

**Comment by Alkl58** [comment]
You can try the latest AppVeyor Build: [click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master) (only replace the main .exe file)

I am going to close this Feature Request, as it is implemented. 

If there is any issues with it, feel free to reopen this issue ^^
