### ISSUE TITLE
[Question] About subtitles

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#43]
Hello Alkl58 and thank you for your work on this great program. 

It is actually my standard "go-to" encoding program atm. 😃 
I have several questions about the subtitle section in neav1e.

When I want to encode a series with one or more subtitle tracks already baked in the mkv file (you can select the subtitle in the player), is it necessary to actually activate a subtitle track in neav1e? The thing is that i can't select a track for it because there is no separate subtitle file for it, you know? 

The other question is about the "burn-in" function of neav1e in the subtitle section: What does this option do? I can't find a help menu or mouse-over explanation for it. 

Thank you in advance for answering my questions. 

Kind regards

**Comment by Alkl58** [comment]
> When I want to encode a series with one or more subtitle tracks already baked in the mkv file (you can select the subtitle in the player), is it necessary to actually activate a subtitle track in neav1e?

NEAV1E will extract all subtitle files and activate/populate the Subtitles Tab when selecting an input file:
![grafik](https://user-images.githubusercontent.com/34812414/112311079-93accd00-8ca5-11eb-8785-e2714134b48f.png)

> The thing is that i can't select a track for it because there is no separate subtitle file for it, you know?

It should appear once a video with embedded subtitles is opened. If not there could be a bug, or missing dependencies.

> The other question is about the "burn-in" function of neav1e in the subtitle section: What does this option do?

Burn-In = Hardsub:
Hardsub means that the subs are burnt into the video permanently, they are part of the video so you cannot show/hide them in a player. It’s good for streaming and watching the ep on a mobile device, e.g. smartphones, tablets…

Softsub means you have the video and the subs in one file but you can play them together with a player like Potplayer/VLC. It’s also good because the video is the same one as the raw, it’s not altered by converting. You can show/hide the subtitles the way you want to.

**Comment by Palulukas** [comment]
Hello Alkl58 and thank you for your quick answer. 

I just double checked: NEAV1E does populate the subtitle Tabs when an input file is selected but when you change input and output for a second encoding (for example the _next_ anime series), it is still filled with the Tabs from the first encoding. 

Do I then have to manually deactivate the subtitle tracks?

Thank you in advance for your answer.

**Comment by Alkl58** [comment]
As you can see it resets the subtitle tab when selecting a different input:

https://user-images.githubusercontent.com/34812414/112466739-74c23f80-8d66-11eb-9ea8-3dddd14c1779.mp4

**Comment by Palulukas** [comment]
Hello Alkl58, 

thank you for your explanations and examples. 
I'm not shure if I'm doing it wrong but I attached a specific case where embedded subs are not recognized. 
I checked with my player of choice and it has selectable subtitles. 
Please see the files below. 

Kind regards
![sub01](https://user-images.githubusercontent.com/11398289/114156696-221a8300-9923-11eb-9050-9d7c2a96339d.jpg)
![sub02](https://user-images.githubusercontent.com/11398289/114156700-22b31980-9923-11eb-9d70-c5ba97ed2491.jpg)
![sub03](https://user-images.githubusercontent.com/11398289/114156701-234bb000-9923-11eb-83ed-b539f83b0d74.jpg)
![sub04](https://user-images.githubusercontent.com/11398289/114156702-234bb000-9923-11eb-9d82-bfd198bad0db.jpg)

**Comment by Alkl58** [comment]
It seems that there is currently no function for "SUB" Subtitles:
https://github.com/Alkl58/NotEnoughAV1Encodes/blob/abcc1514f402d661d57e0548b25839cd1b07c2c2/NotEnoughAV1Encodes/MainWindow.xaml.cs#L1856

I will look into how to implement it in the next days ^^
Many Greetings

**Comment by Alkl58** [comment]
Could you provide the source file, can't somehow find a video file with this type of subtitles.

**Comment by nate-moo** [comment]
I encoded a batch the other day and it didn't include any subtitles that were originally with the videos, which I had to manually add. was this just a bug, or is it intentional, or is it something that I forgot to do?

**Comment by Palulukas** [comment]
Hello Alkl58, 

Is there  a way to write you a pm with link to the source files?

Greetings

**Comment by Alkl58** [comment]
You can contact me on Discord: https://discord.gg/yG27ArHBFe
If this is not ok, we have to figure something else out.

**Comment by nate-moo** [comment]
Has there been any progress on selecting subs for copying the stream to output file?

**Comment by Alkl58** [comment]
No, but it's on my to-do list.

**Comment by Alkl58** [comment]
A new version has been released: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.0
It should by default have subtitles enabled in batch mode, as long the container is MKV.
I am closing this issue, as this is quite an old thread. Feel free to open a new issue.
