### ISSUE TITLE
Trim start settings are ignored when using Advanced settings

### ISSUE THREAD

**Issue by dado023** [Alkl58/NotEnoughAV1Encodes#44]
Time marks in TRIM START and TRIM END are not applied/used  when encoding.
See here https://i.imgur.com/kMRGHwd.png

**Comment by Alkl58** [comment]
You have not enabled Trimming.

![grafik](https://user-images.githubusercontent.com/34812414/112450898-29ebfc00-8d55-11eb-8849-8a551e234a23.png)

**Comment by dado023** [comment]
> You have not enabled Trimming.
> 
> ![grafik](https://user-images.githubusercontent.com/34812414/112450898-29ebfc00-8d55-11eb-8849-8a551e234a23.png)

Thank you....i got it mixed with subtitles, so was thinking its subtitle related.
