### ISSUE TITLE
Installer does not purge old version

### ISSUE THREAD

**Issue by cewbdex** [Alkl58/NotEnoughAV1Encodes#45]
![image](https://user-images.githubusercontent.com/9021297/112833334-dd772800-9096-11eb-9c9a-f2b01f6ee932.png)
Would be probably better to remove it.

**Comment by Alkl58** [comment]
Thanks for the bug report ^^
I will try to get the automatic uninstall working for the next release, until then I recommend removing it manually!
Many Greetings

**Comment by Alkl58** [comment]
The new installer used in v1.8, which can be downloaded [here ](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v1.8), now will purge already installed versions. Due to a technical limitation this will only work with v1.7 and newer.
Many Greetings
