### ISSUE TITLE
Splitting strategy suggestion

### ISSUE THREAD

**Issue by Seedmanc** [Alkl58/NotEnoughAV1Encodes#46]
As I understand it, the ffmpeg method splits on every scene change regardless of how many chunks are required for a given worker count. I believe this is not an optimal way to do it, especially since we can't assume that ffmpeg's scene detection takes the same decisions as AV1's and the threshold is arbitrary. As such we get a lot of extra keyframes, wasting the bitrate and hurting the decisions that codec would have made if it was able to look ahead past the next enforced split.

Instead, why not split the minimum amount of times required for a needed concurrency? So if we set 2 workers, ffmpeg should only look for a scene change around the middle of the video, splitting it into 2 roughly equal chunks, and so on. I've measured SSIM of the equal chunks strategy VS ffmpeg scene detection and there are noticeable quality drops in the latter.

**Comment by Alkl58** [comment]
It might sound good, for me and you, but I had a similar thing a long time ago, where the chunked splitting was set to Video Length divided by the worker count.
People where really not happy as this reduced drastically the ability to resume the aborted encoding process. (NEAV1E skips finished encoded chunks).
The most easy way for people interested in the behavior you described is to just set the equal chunking to a value which results in exactly the chunk count required for encoding concurrent.

**Comment by Seedmanc** [comment]
How strange, I've never considered aborting and resuming encoding at all. Were the aborts caused by mistakes/crashes or were people just splitting long videos over several days of encoding if it doesn't fit overnight? Either way I would rather split the source video myself and spread it over days rather than reducing quality.
