### ISSUE TITLE
'start encode' button not working

### ISSUE THREAD

**Issue by brigazvi** [Alkl58/NotEnoughAV1Encodes#48]
version 1.8
windows 20h2.

i press the button, it make the sound, but nothing happening. i press the pause button or the stop button and i get the message "encode has not started yet!".

i tried to change the settings, but nothing happens.
the original settings:
aomenc. speed 0. lowest file size. 2 passes.

**Comment by Alkl58** [comment]
More than two month passed with no answer / log file.

Closing this issue. Feel free to reopen it.
