### ISSUE TITLE
At the muxing stage of the encode it throws an error Muxing failed. Video output not detected!

### ISSUE THREAD

**Issue by IITuxtmuxII** [Alkl58/NotEnoughAV1Encodes#52]
**Describe the bug**
At the muxing stage of the encode it throws an error Muxing failed. Video output not detected!
Common issue:
usw. (2 times reinstalled)
**To Reproduce**
Just start an Encode and in the final stages ist fails.

**Expected behavior**
A finished AV1 encode of S00E01 of Grenadier.^^
**Screenshots**
https://i.ibb.co/B67wfNk/2021-08-03-20-45-50.jpg
**Log File**
https://ghostbin.com/paste/BUnnr

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - NEAV1E Version: v1.9

**Additional context**

**Comment by MartinEesmaa** [comment]
Hello, Paul. My name is Martin Eesmaa.
Please make sure that it is saved temp folder of NEAV1E.
Copy and paste path into Windows Explorer:
%userprofile%\appdata\local\temp\neav1e

Please select folder same as source video file name.
Have a look of example temp folder of screenshot:
![exampletempfolderofneav1e](https://user-images.githubusercontent.com/88035011/129181353-67d53bf4-f4b0-48f5-850b-6eaa258d3024.png)
If you have temp.mkv and Audio (folder)/audio.mkv, make sure to play first video, then audio to verify.
After you verified of two files are same between original and AV1. Merge audio and video into completed your AV1 video by using MKVToolNix GUI latest version. Please reply me, if you had any issues for me.

Regards
- Martin Eesmaa

**Comment by Alkl58** [comment]
Hello IITuxtmuxII,

sorry for the late reply.

From the pictures you provided it seems that the video is interlaced, is that correct? If yes, please set the Deinterlacer under "Filters" -> "Deinterlace".

If not, try to follow the steps which MartinEesmaa described. 
In your case the files should be located under `M:\Temp\neae`.

A really helpful debugging step would be for you to execute the muxing commands manually to see the errors.
You would have to go into the directory `%appdata%\NotEnoughAV1Encodes\Apps\mkvtoolnix` and open CMD there (click into the Path window of Explorer, type cmd and hit enter) and execute the following command: 
```
mkvmerge.exe --output "D:\Movie\Video\Grenadier S01 German Opus DL 576i DVDrip AV1-Pseudo\GRENADIER - S00E07 - Alternate Opening AV1.mkv"  --language 0:und --default-track 0:yes "M:\Temp\neae\GRENADIER - S00E07 - Alternate Opening\temp.mkv" --default-track 0:yes "M:\Temp\neae\GRENADIER - S00E07 - Alternate Opening\Audio\audio.mkv"  --language 0:deu --track-name 0:"" --default-track 0:no "M:\Temp\neae\GRENADIER - S00E07 - Alternate Opening\Subtitles\pgs_dvd_0.sup" --language 0:deu --track-name 0:"" --default-track 0:no "M:\Temp\neae\GRENADIER - S00E07 - Alternate Opening\Subtitles\pgs_dvd_1.sup"
```

I am currently trying to implement that it writes the actual error message into the log file.

**Comment by MartinEesmaa** [comment]
Oh...he did custom temp path.
