### ISSUE TITLE
[BUG] Custom Bit-Depth not working in batch mode

### ISSUE THREAD

**Issue by Fraxlin** [Alkl58/NotEnoughAV1Encodes#54]
**Describe the bug**
Bit-Depth resets itself to default value in batch executions.

**To Reproduce**
1. Set a custom Bit-Depth in the Video tab (for ex. 10-bit)
2. Set everything you need for a batch execution (but don't start it yet)
3. Position yourself in the Video tab again
4. Start the execution: as soon as you click "Start", the Bit-Depth value reset itself to 8-bit. In the log files you can find evidence of the default 8-bit depth instead of the custom one.

**Expected behavior**
Custom Bit-Depth should not reset itself to the default value.

**Specs:**
- OS: Win10 20H1
- NEAV1E Version: v1.9
 
**Image**
 ![Bit-Depth](https://user-images.githubusercontent.com/88848258/129238597-8e2369b2-d355-4d90-8b1a-9560e602b6d4.gif)

**Comment by Alkl58** [comment]
Issue should be resolved.

You can try the fix with the following Build: ![click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts) 
(for this you need to extract `NotEnoughAV1Encodes.exe` and the `MediaInfo` subfolder into your current installation.)

Many Greetings

**Comment by Alkl58** [comment]
For future references:
https://github.com/Alkl58/NotEnoughAV1Encodes/blob/4d14b9d40e60134bcde946e4b23a89132d0200c5/NotEnoughAV1Encodes/MainWindow.xaml.cs#L180
Batch Mode is now working completely differently and there is currently no code which will interfere with Custom Bit-Depth.
