### ISSUE TITLE
[BUG] custom bit depth from 10 bit to 8 bit default resets

### ISSUE THREAD

**Issue by MartinEesmaa** [Alkl58/NotEnoughAV1Encodes#55]
**Describe the bug**
Trying to use batch file mode and try to encode for 10 bit aomenc

**To Reproduce**
1.  I clicked Source, Batch File and selected source folder
2.  I set to 10 bit depth and YUV 420
3. I hit Start encode
4. Resets to 8 bit depth back before encode in batch file mode.

**Expected behavior**
It won't let me force 10 bit, it only encodes 8 bit for batch file mode.

**Screenshots**
![errorofnotenougav1encodes](https://user-images.githubusercontent.com/88035011/130205305-b55cd7a0-1ffc-422b-a9b0-9d77d2058186.gif)

**Log File**
If possible, upload the log generated by the program here.

**Desktop (please complete the following information):**
 - OS: Win10 20H1
 - NEAV1E Version: v1.9

**Additional context**

**Comment by Alkl58** [comment]
Duplicate? https://github.com/Alkl58/NotEnoughAV1Encodes/issues/54

**Comment by MartinEesmaa** [comment]
Well I mean the build is saying Non-Image content-type returned

**Comment by Alkl58** [comment]
No Reason to open a new issue.
Fixed the link the supposed fix from the other issue report.

**Comment by MartinEesmaa** [comment]
Thank you! Now it worked for unreleased version of future.
