### ISSUE TITLE
[option request] more workers allowed

### ISSUE THREAD

**Issue by plonk264** [Alkl58/NotEnoughAV1Encodes#56]
is there a chance you could allow more workers than is currently allowed? maybe by a hidden/ini option somewhere?

reason i ask is i'm only getting ~55% cpu usage encoding VP9 on my 1700X with the 8 max workers allowed

![image](https://user-images.githubusercontent.com/4464684/130560306-84ae8e9a-ff6a-496c-9e1b-606f51801ee9.png)

**Comment by Alkl58** [comment]
You can try the feature with the following Build: [click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts) 
(for this you need to extract NotEnoughAV1Encodes.exe and the MediaInfo subfolder into your current installation.)

Many Greetings

**Comment by Alkl58** [comment]
Added in 36190e65b05c544ce0d49e6f09d8a03b5efbc89f and fixed in 87d451cdcd9e0fb745838ea37aae262326f1494c and will be in the next v2.0 release.
