### ISSUE TITLE
Constrained quality mode for VP9

### ISSUE THREAD

**Issue by iPaltus** [Alkl58/NotEnoughAV1Encodes#57]
Please add constrained quality (CQ) option for VP9 - both -crf and bitrate, it's recommended for VOD by Google https://developers.google.com/media/vp9/bitrate-modes#cq and shows best quality/size ratio.
Need to add both for example -b:v 1500K -crf 33 to ffmpeg command line. 

> For most content types, we recommend using constrained quality (CQ) mode, with bitrate caps. Most videos contain a mix of high-motion scenes (e.g., action sequences) and scenes with less detail (e.g., conversations). CQ mode allows the encoder to maintain a reasonable quality level during longer, easier scenes (without wasting bits), while allocating more bits for difficult sequences.
> Nonetheless we must still constrain the process by providing an upper range -- otherwise there may as well be no compression at all! We can also set a lower range, where even if the image is black and the encoding process has almost nothing to do we will still throughput that data, perhaps less efficiently than we could, but with the end result that even the black is not significantly compressed and look "very black".

The following FFmpeg command-line parameters are used for CQ mode:

-b:v <arg>	Sets target bitrate (e.g. 500k)
-minrate <arg>
-maxrate <arg>	Sets minimum and maximum bitrate.
-crf <arg>	Sets maximum quality level. Valid values are 0 to 63, lower numbers are higher quality.

**Comment by Alkl58** [comment]
Added in https://github.com/Alkl58/NotEnoughAV1Encodes/commit/a7968566debebcb781c335adf1bfb21de1cfe093
