### ISSUE TITLE
Multiple file encoding simultaneously

### ISSUE THREAD

**Issue by iPaltus** [Alkl58/NotEnoughAV1Encodes#59]
It will be useful to let multiple file encoding simultaneously instead of splitting 1 file. In batch mode it will be same parallel encoding by several workers, but no need to split file to temp directory, encoding audio separately and the sync.

**Comment by Alkl58** [comment]
Added in 6d022778cb1fcfb43f7234c52aed78adfc49de69 and will be in the next v2.0 Release.
