### ISSUE TITLE
Changable Framerate

### ISSUE THREAD

**Issue by Freakboo** [Alkl58/NotEnoughAV1Encodes#61]
Unable to change frame rate for ex: from 60 to 30

be able to adjust frame rate preferably with an option for constant or peak.

**Describe alternatives you've considered**
reducing frame rate with other encoder.. then encode again

want to reduce my file size a bit more by removing frame rate for video that doesnt need to have a high framerate.

**Comment by Alkl58** [comment]
Added in f07c90a76b43ac41209cd08561eb207671704774 and will be in the next v2.0 Release.
