### ISSUE TITLE
[BUG] NEAV1E 1.9 will not start not even the portable version

### ISSUE THREAD

**Issue by IITuxtmuxII** [Alkl58/NotEnoughAV1Encodes#64]
Hi I am back again -_-
**Describe the bug**
I have not used NEAV1E in around a month and yesterday I wanted to use it and ist just does not want to start.
It shows up in taskmanager, but instandly disapieres

**Expected behavior**
It should start

**Desktop (please complete the following information):**
 - OS: Win10 20H1
 - NEAV1E Version: v1.9

**Additional context**
I have installed the dependencies twice and downloaded the portable version, but no luck. TnT

**Comment by MartinEesmaa** [comment]
Hello, @IITuxtmuxII! I am very sorry to say that portable version is not working on your computer. Portable version may be not work, but I tested Windows Sandbox to run portable version latest of NEAV1E, it works, but I think that's weird that portable version can't start on your computer :/. It is recommend to download full setup of latest version. Did you try full setup of NEAV1E to run?

**Comment by IITuxtmuxII** [comment]
yes I have tried the fullsetup and still the same problem.
sadly I have no clue why

**Comment by MartinEesmaa** [comment]
Maybe something is wrong with your computer. Try reinstall again of [](https://dotnet.microsoft.com/download/dotnet-framework/net472) (Microsoft .NET Framwork, latest version) and [](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) (Microsoft Visual C++) for latest version. If it fails after reinstalled two important things to fail start NEAV1E.

Try maybe run command prompt in admin, type `sfc /scannow`
If sfc /scannow did not work and you tried to open NEAV1E also not work, try type
`DISM /Online /Cleanup-Image /CheckHealth`
`DISM /Online /Cleanup-Image /ScanHealth`
`DISM /Online /Cleanup-Image /RestoreHealth`

If DISM success, restart your computer and start NEAV1E.
If not work, maybe try unstable version of NEAV1E?
Let me know please, reply me.

- Martin Eesmaa

**Comment by IITuxtmuxII** [comment]
Hi Thanks for the reply
I have tried the CLI commands, but no like.
Does the dotnet framework have to be 4.7.2 or can it be 5, because I get an error that dotnet found that version or a newer version on the computer and I know that I have dotnet 5 installed.
and I reinstalled  vc_redist.
and I have tried the QT version that works for  some reson. -__-
regardes,
Paul

**Comment by Alkl58** [comment]
Hi @IITuxtmuxII 

could you look in the Event Viewer of Windows, to see if there is a crash log? 

Many Greetings

**Comment by IITuxtmuxII** [comment]
Hier are the crashlogs of AV1 stuf mybe it helps?

https://ghostbin.com/paste/a1oqL
https://ghostbin.com/paste/S1bJg


Thanks a lot for the help, really appreciate it.^^

**Comment by Alkl58** [comment]
Thats a pretty weird issue, apparently it get's an `System.ArgumentException`:

```
Ausnahmeinformationen: System.ArgumentException
   bei System.IO.Path.CheckInvalidPathChars(System.String, Boolean)
   bei System.IO.Path.Combine(System.String, System.String)
   bei NotEnoughAV1Encodes.CheckDependencies.GetFullPath(System.String)
   bei NotEnoughAV1Encodes.CheckDependencies.Check()
   bei NotEnoughAV1Encodes.MainWindow.Startup()
```

It's literally thrwoing an exception upon checking for the dependencies, I myself never experienced that issue.

So far it always asked the user to download ffmpeg if doesn't find it.

How does the full path to the extracted folder look like?

**Comment by IITuxtmuxII** [comment]
OK I have no clue what is wrong with it, but here

C:\Users\Paul\AppData\Roaming\NotEnoughAV1Encodes
https://ghostbin.com/paste/iDOhX

**Comment by Alkl58** [comment]
Yeah... I can't find the issue. 

You may try reinstalling NEAV1E completly, by also removing all contents of the install dir and re-extracting the Build from the releases tab. (Not the AppVeyor ones)

NEAV1E is currently being entirely rewritten in .NET Core, which means that the current version on .NET Framework won't be maintained and is being replaced once the v2 Branch is ready.

**Comment by IITuxtmuxII** [comment]
It did not help, but thanks a lot for the help and all.
Danke für die Hilfe.
I am very exited for v2.

regardes,
Paul
