### ISSUE TITLE
[Feature] SVT-VP9 Support

### ISSUE THREAD

**Issue by 57382** [Alkl58/NotEnoughAV1Encodes#66]
https://www.phoronix.com/scan.php?page=news_item&px=SVT-VP9-Open-Source

**Comment by Alkl58** [comment]
Will try to do, once the 2.0.0 Version has been released.

**Comment by Alkl58** [comment]
I had everything implemented and ready to test. However it seems that libsvt_vp9 produces empty files: https://github.com/m-ab-s/media-autobuild_suite/issues/1807

I will try the non ffmpeg version in a few days.

**Comment by n00mkrad** [comment]
Pretty sure SVT-VP9 is inferior to VPX anyways, I'm not sure if it's worth implementing.

**Comment by Alkl58** [comment]
A bit late for the follow up, however after some testing it seems that `SvtVp9EncApp` doesn't really work. 

It seems to encode, however the resulting video file has horizontal sync issues - the YUV components are not overlaying correctly and shitfting horizontal at different speeds.
![vlcsnap-2022-01-26-17h59m46s730](https://user-images.githubusercontent.com/34812414/151210410-adde143c-7869-4978-ad31-a210fe4a37a7.png)
