### ISSUE TITLE
running out of disk space when using large files

### ISSUE THREAD

**Issue by LukasLohmar** [Alkl58/NotEnoughAV1Encodes#7]
i was trying neav1e and ran into some problems with larger files where the splitting process used way to much disk space

the file i used was a h265 with a resolution of 3840x2160@23.976 in 10 bit and roughly 2 hours of runtime
neav1e tried to split the file into chunks with 864 seconds length which results in 67gb for each chunk

**Comment by Alkl58** [comment]
Please try the latest AppVeyor Build: https://ci.appveyor.com/project/Alkl/notenoughav1encodes/branch/master/artifacts
The latest "Release" had the bug that it will reencode to lossless regardless what you choosed.
Please tell me if it works :)

**Comment by LukasLohmar** [comment]
thank you, this fixed my issue
