### ISSUE TITLE
Muxing failed: Video output not detected. Vsync command failed

### ISSUE THREAD

**Issue by lhulet** [Alkl58/NotEnoughAV1Encodes#72]
"Error: (mkvextract) The file could not be opened for reading: Not a valid Matroska file (no EBML head found)." My source file isn't AV1, it is H265. So it makes sense that I get this error. Because the vsync.txt file is missing, the merge fails.

I'm on v1.9

**Comment by Alkl58** [comment]
Could you send the log file? (Should be in the output directory of the video)

Also: Is your source video a .mkv file?

**Comment by lhulet** [comment]
[haloinfinite.exe 2021.12.06 - 00.34.19.05.DVR-00.05.01.999-00.05.04.999-newavtest.mp4.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/7699013/haloinfinite.exe.2021.12.06.-.00.34.19.05.DVR-00.05.01.999-00.05.04.999-newavtest.mp4.log)

Sorry for the long file names. Source videos are mp4 files encoded in HEVC.

**Comment by Alkl58** [comment]
Yeah... first of all: VFR is only supported with MKV source videos.

When using other input types (in your case mp4), you will need to make it constant framerate (if its really VFR) and disable VFR.

Reasoning is that extractMKV can only extract VFR Data from MKV files.

**Comment by lhulet** [comment]
Oh lol. Thank you!

**Comment by lhulet** [comment]
Also, that log file wasn't right. This was what I was looking for:
[test.mkv.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/7699039/test.mkv.log)
