### ISSUE TITLE
GUI multi-language support

### ISSUE THREAD

**Issue by wcxu21** [Alkl58/NotEnoughAV1Encodes#73]
Hi, I am from China, can you add multi-language support to this application?

I can help you translate the Chinese language and also help you promote this free app in China.

Thank you for your work!

**Comment by Alkl58** [comment]
Yes, multi language support it's been in the workings.

For the UI elements I have put the english translations inside here: [en-US.xaml](https://github.com/Alkl58/NotEnoughAV1Encodes/blob/master/NotEnoughAV1Encodes/resources/lang/en-US.xaml)

The plan is to also put all the (error) messages inside a language file, however I didn't do that one yet.

However, I will have to further investigate to see what's best practice and how to implement actual multi language support. Which I plan to do today.

**Comment by wcxu21** [comment]
Thank you for your work, I will continue to pay attention to your project to complete the Chinese translation.

**Comment by Alkl58** [comment]
Took a bit longer than expected, however it's now save to add other languages.

If you want to translate to Chinese, you have to create a Resource File, named `Strings.zh.resx` inside the [resources/lang](https://github.com/Alkl58/NotEnoughAV1Encodes/tree/master/NotEnoughAV1Encodes/resources/lang) folder.

You can do that by duplicating the base file `Strings.resx` and renaming it.

I know, that there are different variants of chinese, so depending on what type you do, you can instead name the file:

- `Strings.zh-TW.resx` for Chinese (Taiwan)
- `Strings.zh-CN.resx` for Chinese (People's Republic of China)
- `Strings.zh-HK.resx` for Chinese (Hong Kong S.A.R.)
- `Strings.zh-SG.resx` for Chinese (Simplified, Singapore)
- `Strings.zh-MO.resx` for Chinese (Traditional, Macao S.A.R.)

(I don't expect from you to do different versions)

Either you can make a PR or upload the file directly here.

If you know C#, you can also add the necessary references here: https://github.com/Alkl58/NotEnoughAV1Encodes/blob/893112cfe6e0abe28d348a4454ffef0977deaaa4/NotEnoughAV1Encodes/Views/ProgramSettings.xaml.cs#L40 and here: https://github.com/Alkl58/NotEnoughAV1Encodes/blob/893112cfe6e0abe28d348a4454ffef0977deaaa4/NotEnoughAV1Encodes/Views/ProgramSettings.xaml.cs#L103 

Many Greetings

**Comment by wcxu21** [comment]
thank you for your reply.
Generally, in Mainland China, the resource used is zh-CN, and other Chinese regions use their own names as needed.

**Comment by Alkl58** [comment]
Thanks for your help, have a nice day!
谢谢你的帮助，祝你有个愉快的一天
