### ISSUE TITLE
[BUG] Running queue element not present in gui after edit

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#74]
**Describe the bug**
While running a encode, you can edit queue elements, even the running one. 
I've done it because I saw that I set a wrong video option. 
Excepting to restart the encode with new settings, the element dissappeared from the queue but my computer kept encoding "something". 

**To Reproduce**
1. Add element to queue
2. Start encode
3. Edit currently encoded element in queue
4. Save edits and find yourself the messing element in queue :D

**Expected behavior**
Not entirely clear but I would expect to restart the current encoding with the fresh settings.

**Screenshots**
See below. Please don't get irritated by low cpu usage. In the moment I took the screenshot, the invisible encoding must have finished. ;-) But as you can the in the diagrams, the cpu usage was all cores maxed out just a few seconds ago. 

**Log File**
If possible, upload the log generated by the program here.

**Desktop (please complete the following information):**
 - OS: Win10 20H1
 - NEAV1E Version: 2.0.0
![neav1e_bug](https://user-images.githubusercontent.com/11398289/146675322-e33eb752-4429-4c7a-a199-c521b262fe5c.jpg)

**Comment by Alkl58** [comment]
Oh well...

Yeah, you aren't supposed to edit queue elements, when the encode is running.
When clicking edit item, it moves the item from the queue, to the "GUI" if it makes sense and deletes the queue item.
The idea was, that users could edit the item and then re-add it to the queue.

I should probably disable those options, once the encode has started - the queue system itself needs improvment aswell, as it doesn't check for new queue items, after the encode has started.

**Comment by Alkl58** [comment]
The new releases prevents users doing what you did ^^

Just as final note: After clicking edit item, you have to re-add it with "Add to Queue".

**Comment by Palulukas** [comment]
Hello Alkl58, 
thank you for your explanations. Maybe you can modify the "Add to Queue" button to "Re-Add to Queue" while editing a queued item? Or something to remind the user to re-add after the editing is done.

Regards
