### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Palulukas** [Alkl58/NotEnoughAV1Encodes#75]
**Is your feature request related to a problem? Please describe.**
NEAV1E currently names queued encodings very oddly. It seems like it randomly appends characters at the end of the original file name. 

**Describe the solution you'd like**
I would like to see the filne name appendix from version 1,9 with was like "filename.mkv_aomenc.mkv". 
With this layout of filename it was very easy to bulk-rename entire folders with encoded files. 

**Describe alternatives you've considered**
An awesome solution would be to let the user choose the appended suffix before encoding is queued or started. :-)

**Comment by Alkl58** [comment]
Yes, the current behavior is to add a random string (Unique Project Identifier).

I planned to add those things you described on Preset level.

**Comment by Alkl58** [comment]
![grafik](https://user-images.githubusercontent.com/34812414/146690121-982111e6-042c-4181-aff2-7d3fe4809416.png)

Is in the new release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.1
