### ISSUE TITLE
[BUG] GUI frozen

### ISSUE THREAD

**Issue by neoOpus** [Alkl58/NotEnoughAV1Encodes#76]
**Describe the bug**
the graphic user interface frozen after clicking the start button

**To Reproduce**
add batch files to the queue, then click start

**Expected behavior**
interaction is possible with the user interface will be able to see progress

 - OS: [Win11 20h1Latest Insider Beta]
 - NEAV1E Version: [e.g. v2.0]

**Additional context**
it's possible, please add back the pause button like in the previous version

**Comment by Alkl58** [comment]
Fixed in Commit: https://github.com/Alkl58/NotEnoughAV1Encodes/commit/78042e23dca399ec401a6f871dbc319f2f87b174 (Technically the UI Thread is freezing, the encoding thread works however)

**Comment by neoOpus** [comment]
> Fixed in Commit: [78042e2](https://github.com/Alkl58/NotEnoughAV1Encodes/commit/78042e23dca399ec401a6f871dbc319f2f87b174) (Technically the UI Thread is freezing, the encoding thread works however)

Yes I confirm

**Comment by Alkl58** [comment]
Fixed Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.1

**Comment by neoOpus** [comment]
Thank you so much this is incredible how fast you fix it
