### ISSUE TITLE
[Feature] random naming for batch

### ISSUE THREAD

**Issue by neoOpus** [Alkl58/NotEnoughAV1Encodes#77]
Please make the random string added to the file name to between accolades, this way it will be easier to rename the file by removing the string via regex or simple {*}

Or It would be great if there is a unique identifiable pattern that will not occur in conventional file name, so it can be easy to find and remove

**Comment by Alkl58** [comment]
![grafik](https://user-images.githubusercontent.com/34812414/146690155-554b4492-334b-46f4-807e-1f65e7e20b16.png)

Is in the new release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.1
