### ISSUE TITLE
[Feature] Keyframes GUI

### ISSUE THREAD

**Issue by neoOpus** [Alkl58/NotEnoughAV1Encodes#78]
Hello again, 

I compressed some videos and found it hard to seek since libaom default to 9999 keyframes interval... it would be great if you can implant in the UI how to tweak this by considering the frame rate of the video, so it becomes a better alternative to doing it manually via the -g command

Thank you :)

**Comment by Alkl58** [comment]
Note that I haven't tested it yet, as I am waiting for a heavy GPU intensive task to finish, so I can start my VM to test it.

**Comment by Alkl58** [comment]
Implementation seems to work, closing this issue.
