### ISSUE TITLE
Constant Quality bar behavior inverted

### ISSUE THREAD

**Issue by ibhh** [Alkl58/NotEnoughAV1Encodes#8]
The behavior of the bar is inverted, thus choosing high quality will produce low quality and the other way round.
The functionality is given and the encoding working.

Win10 Version	10.0.18363 Build 18363
GUI Build Version (can be found under Program Settings): Pre-Release v0.9
Encoder you are using: aomenc
Encoding Settings:  RF 19 (expect the same behaivor as h265/HEVC) -> Same behavior
`--cpu-used=7 --bit-depth=10 --threads=8 --tile-columns=0 --tile-rows=0 --kf-min-dist=0 --kf-max-dist=240 --lag-in-frames=25 --max-reference-frames=7 --color-primaries=unspecified --transfer-characteristics=unspecified --matrix-coefficients=unspecified --i420  --tune=psnr --sharpness=0 --row-mt=1 --enable-keyframe-filtering=1 --aq-mode=0 --auto-alt-ref=0 --frame-boost=0 --end-usage=q --cq-level=19`
Audio Settings if used: aac 160kbits
General Video Information (Framerate / Resolution - MediaInfo Screenshot would be nice): 720p30fps

**Comment by Alkl58** [comment]
Thanks for the bugreport ^^
Will fix it as soon as possible.
