### ISSUE TITLE
Muxing to MP4 container is still Matroska

### ISSUE THREAD

**Issue by Vereor** [Alkl58/NotEnoughAV1Encodes#82]
With the new 2.0.2 version there is no longer an option/settings to change the container to MP4
When choosing the destination to save as MP4 it looks to be naming the extension only and effecting the muxing container

`12/30/2021 1:27:26 PM : INFO  - Input: D:\VT\IN\clips\2021-12-30 03_15 (1)-00.23.39.466-00.26.12.000.mp4`
`12/30/2021 1:27:26 PM : INFO  - Output: D:\VT\IN\clips\2021-12-30 03_15 (1)-00.23.39.466-00.26.12.000.mp4`
`12/30/2021 1:39:37 PM : DEBUG - VideoMuxer.Concat() => Command: ffmpeg.exe -y -f concat -safe 0 -i "C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\chunks.txt" -c copy "C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\temp_mux.mkv"`
`12/30/2021 1:39:37 PM : DEBUG - VideoMuxer.Concat() => MuxWithMKVMerge? : True`
`12/30/2021 1:39:37 PM : DEBUG - VideoMuxer.Concat() => AudioCommand?    : --default-track 0:yes "C:\Users\John\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\Audio\audio.mkv"`
`12/30/2021 1:39:37 PM : DEBUG - VideoMuxer.Concat() => SubsCommand?     : `
`12/30/2021 1:39:37 PM : DEBUG - VideoMuxer.Concat() => VFRCommand?      : `
`12/30/2021 1:39:38 PM : DEBUG - VideoMuxer.Concat() => Exit Code: 0`
`12/30/2021 1:39:38 PM : DEBUG - VideoMuxer.Concat() => STDOUT: mkvmerge v63.0.0 ('Everything') 64-bit`
`'C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\temp_mux.mkv': Using the demultiplexer for the format 'Matroska'.`
`'C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\Audio\audio.mkv': Using the demultiplexer for the format 'Matroska'.`
`'C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\temp_mux.mkv' track 0: Using the output module for the format 'AV1'.`
`'C:\Users\Me\AppData\Local\Temp\NEAV1E\uTGHgKKFocumqnp\Audio\audio.mkv' track 0: Using the output module for the format 'Opus'.`
`The file 'D:\VT\OUT\AV1\2021-12-30 03_15 (1)-00.23.39.466-00.26.12.000-AV1-2.mp4' has been opened for writing.`

**Comment by Alkl58** [comment]
To be honest, I didn't noticed that MKVMerge ignores the output container. It didn't gave any warnings so I figured that it support mp4 output. 

Looking at the MediaInfo makes it pretty obvious:
```
Complete name                            : C:\Users\VM\Desktop\test.mp4
Format                                   : Matroska
FileExtension_Invalid                    : mkv mk3d mka mks
```

I am currently working on implementing ffmpeg muxing for this case.

**Comment by Alkl58** [comment]
Fixed Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.3
