### ISSUE TITLE
[BUG] Changing Reencode Method has no effect and only uses x264, which makes files 25x larger than the source file

### ISSUE THREAD

**Issue by Mfarooq360** [Alkl58/NotEnoughAV1Encodes#83]
**Describe the bug**
When trying to change the Reencode Method to something other than x264 and adding it to queue, it'll still use x264 no matter which option you pick. This has been discovered to occur from the logs and from examining the Temp video files.

**To Reproduce**
1. Add source clip
2. Change Reencode Method to anything besides x264
3. Add to Queue and Start
4. Examine logs which say libx264 is used, Temp video files show encoded with H264.

**Expected behavior**
Changing Reencode Method should affect how the video is first Reencoded like in previous versions.

**Screenshots**

![neav1e utvideo](https://user-images.githubusercontent.com/97059075/148014782-b48a15cf-f634-48b7-a60c-127def42c05d.PNG)

**Log File**
[Desktop 2021.10.15-21.01.27 DVR-36.mp4.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/7803838/Desktop.2021.10.15-21.01.27.DVR-36.mp4.log)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - NEAV1E Version: 2.0.2

**Additional context**
I tried to change the Reencode Method due to x264 taking almost exactly 25x more storage than the source video every time, and large videos that are multiple gigabytes in size can fill up my entire hard drive using x264 for some reason. For example, a 20gb recording can have temp files as large as 500gb with x264.

**Comment by Alkl58** [comment]
Fixed Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.4
Many Greetings
