### ISSUE TITLE
[BUG] Muxing stuck at 100% despite being finished

### ISSUE THREAD

**Issue by nate-moo** [Alkl58/NotEnoughAV1Encodes#85]
**Describe the bug**
The final Muxing step never finishes, only sticks at Muxing 100% despite showing in log file that Muxing finished in 4 seconds.

**To Reproduce**
1. Encode something
2. Profit 

**Expected behavior**
Says encode finished

**Screenshots**

**Log File**
If possible, upload the log generated by the program here.
https://www.toptal.com/developers/hastebin/ilupifafip.yaml

**Desktop (please complete the following information):**
 - OS: Win10 21H1 HOME
 - NEAV1E Version: 2.0.3 & 2.0.4

**Additional context**
Has never shown complete only Muxing 100%

**Comment by Mfarooq360** [comment]
Having a similar problem where muxing is technically completed, and the video is usable, but the application shows it’s still muxing at 100.03%.

**Comment by Alkl58** [comment]
Added in Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.5

Many Greetings
