### ISSUE TITLE
Maybe Can add SVT-HEVC Encoder and SVT-VP9 Encoder

### ISSUE THREAD

**Issue by KelvinSoh8** [Alkl58/NotEnoughAV1Encodes#86]
The SVT-VP9 Encoder and SVT-HEVC Encoder Scalable Video Technology Encoder Intel optimized for CPU Processors, Which Get Greatly Improve  Encoder Speed Software Encoding..

**Comment by Alkl58** [comment]
Regarding SVT-VP9: [[Feature] SVT-VP9 Support](https://github.com/Alkl58/NotEnoughAV1Encodes/issues/66)

![grafik](https://user-images.githubusercontent.com/34812414/151332422-fb32e48e-bef5-449b-9cb1-8f2fc8bca5a7.png)

I don't plan to do SVT-HEVC - sorry.
