### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Ichisich** [Alkl58/NotEnoughAV1Encodes#87]
Since 2.0 the  TaskbarItemInfo.ProgressState property is missing.

Given that .net core isn't at fault and even if an accurate progress indicator isn't possible, a simple colour scheme would already a huge improvement.

Green = encoding
Yellow = paused
Red     = error

**Comment by Alkl58** [comment]
Added in Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.5

Might be changed / improved in the future.

Many Greetings
