### ISSUE TITLE
[BUG] "2-Pass encoding" toggle at svt-av1 not working

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [Alkl58/NotEnoughAV1Encodes#89]
When using svt-av1 (both ffmpeg and vanilla), the "2-Pass encoding" toggle does not react to any click. It is stuck at the off state. Is it unsupported or is it a bug? 

 - OS: Windows 11 Pro 21H2
 - NEAV1E Version: 2.0.5

**Comment by Alkl58** [comment]
SVT-AV1 2-Pass encoding is unstable and very experimental - thats why it can't be activated in the GUI.

Many Greetings
