### ISSUE TITLE
No output file file found!

### ISSUE THREAD

**Issue by truefriend-cz** [Alkl58/NotEnoughAV1Encodes#9]
Hi. After open app and select source video and output video and click on Start Encode show this dialog.

Checking Resume Mode not worked too.
Tested on: Pre-Release v0.9-beta

![aaa](https://user-images.githubusercontent.com/7845691/88084839-4364f480-cb85-11ea-9c7e-f1f63181fc1b.jpg)

**Edit:**
This problem have filenames with special chars only. ... ěščřžýáíéúů (czech language chars)

**Comment by Alkl58** [comment]
Are all dependencies in the Apps Folder? (ffmpeg.exe & ffprobe.exe should be under "Apps -> ffmpeg")
Do you have Microsoft Visual C++ Redistributable installed?
How does the Path to your file look like? / How is the file named?

**Comment by Alkl58** [comment]
I can confirm your issue with czech characters.
This is a very special problem, which I can't solve as Visual Studio behaves in unexpected ways.
I recommend to temporary rename your files to non czech chars.

**Comment by truefriend-cz** [comment]
Ok, thanks.
