### ISSUE TITLE
[BUG] svt-av1 (AV1 FFmpeg) encoded files do not transfer HDR data from the source

### ISSUE THREAD

**Issue by RimasRaV1** [Alkl58/NotEnoughAV1Encodes#96]
**Describe the bug**
The newly created 10bit/12bit AV1 video file doesn't have transferred HDR colour tags from the source in the mkv file header or elsewhere, hence the file is recognized by players as SDR. Encoded webm AV1 chunks, on the other hand seem to have proper colour tags - they are recognised as HDR by the player.

**To Reproduce**
1. On Summary tab add HDR video (BT.2020 colour range), select output destination, etc. I choose Reencode method: copy (not reencoding)
2. On Video tab select avt-av1 (AV1 FFmpeg) encoder, 10bi or 12bit bit-depth.
3. Add to queue, start encoding.
4. Play encoded webm chunks - they seem to have HDR information (I test them with PotPlayer, Windows 10).
5. Wait for the encoder to finish - the encoded file does not play as HDR.

**Expected behavior**
File encoded from HDR source with 10bit or more depth encoder should also be HDR.

**Desktop (please complete the following information):**
 - OS: Win10 21H1]
 - NEAV1E Version: 2.0.6

**Comment by Alkl58** [comment]
Can reproduce, it seems to be an issue in the muxing process, as ffmpeg disregards all HDR metadata when concatenating the chunks.

As ffmpeg seems to have a lot of issues regarding HDR metadata, I probably will have to use mkvmerge to apply those data. Will most likely be in a form of an extra tab where users can select all HDR metadata on container level and not on encoder level.

**Comment by Alkl58** [comment]
Just added a new HDR Tab with all relevant settings which are set on container level with MKVMerge:
![grafik](https://user-images.githubusercontent.com/34812414/159167555-7d87e4ec-79b9-473a-bfb3-a15b53986934.png)

**Comment by Alkl58** [comment]
HDR Tab is included in the new [2.0.7 Release](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.7)

**Comment by jriker1** [comment]
Know this is closed but was this done with mkvmerge?  I ask because I thought I read that HDR10 metadata goes beyond placing it in the header of the container or what have you and applying it with tools like this wouldn't be fully compliant or fully honored by the monitor?
