### ISSUE TITLE
Suggestion: Allow Selecting up to Logical Processor Count

### ISSUE THREAD

**Issue by mwgabby-li** [Alkl58/NotEnoughAV1Encodes#98]
[The current code uses Processor.NumberOfCores](https://github.com/Alkl58/NotEnoughAV1Encodes/blob/d6c7c4712c5bea3c2c0cc1d22ff4d1b9666b35c5/NotEnoughAV1Encodes/MainWindow.xaml.cs#L66), the number of physical processors.

I'm not sure if there is a reason behind specifically using physical processor count, but it would be nice to allow people to set the count higher in order to use hyperthreading by using something like [Environment.ProcessorCount](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=net-6.0) instead.

**Comment by Alkl58** [comment]
![grafik](https://user-images.githubusercontent.com/34812414/158083239-bbac0ba7-c816-48c7-9663-d9007a6382ba.png)

That should fulfill the needs.

Generally Multithreading was improved on encoder level, so in my testing there was no need to actually go above the physical core count. However I know that people still may want to override it, so there is an option in the settings page to override it.
